<?
/* Ce fichier contient les parametres de la page a afficher */

/*************************/
/* champs pour affichage */
/*************************/

$champ_1="&lt;div&gt;
&lt;p&gt;&lt;em style=&quot;background-color: transparent;&quot;&gt;&lt;em&gt;Merci pour le s&amp;eacute;jour i&amp;ccedil;i, c'&amp;eacute;tait super ! La piscine est g&amp;eacute;niale et vous &amp;ecirc;tes tr&amp;egrave;s gentils !&lt;br /&gt;&lt;br /&gt;Marylou - France - Juillet 2022&lt;/em&gt;&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;em style=&quot;background-color: transparent;&quot;&gt;&lt;em&gt;Grazie per l'accoglienza e la spendida casa ... curata nei piccoli dettagli come noi amiamo ! Noi vediamo l'ora di tornare...&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;Ines &amp;amp; Roberto - Italie - Juillet 2022&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;em style=&quot;background-color: transparent;&quot;&gt;Pour ceux qui veulent d&amp;eacute;couvrir la r&amp;eacute;gion du Lub&amp;eacute;ron, la Villa Velleron est vraiment bien situ&amp;eacute;e, un accueil chaleureux de la part de Sandra et Urs les propri&amp;eacute;taires des lieux. Une jolie chambre en mezzanine dans le style de la r&amp;eacute;gion, un petit d&amp;eacute;jeuner copieux et complet que demander de plus pour passer un agr&amp;eacute;able s&amp;eacute;jour pour ce dernier we du mois de Mai. De plus, la d&amp;eacute;couverte des&amp;nbsp; villages de Provence, Lourmarin, Saint R&amp;eacute;my de Provence, Gordes et bien d&amp;rsquo;autres sont situ&amp;eacute;s dans un rayon proche de la Villa pour ceux qui ne veulent pas trop se d&amp;eacute;placer.&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;&lt;br /&gt;Nous gardons un excellent souvenir de notre passage chez Sandra et Urs, entour&amp;eacute;s de bienveillance et de joie de vivre ! &amp;Agrave; refaire tr&amp;egrave;s vite...&lt;br /&gt;&lt;br /&gt;Jean-Claude &amp;amp; Corinne - France - Mai 2022&lt;/em&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;div&gt;&lt;em&gt;Une &amp;eacute;tape d&amp;eacute;licieuse, des h&amp;ocirc;tes charmants et attentionn&amp;eacute;s. Literie excellente, un grand calme alors que la maison &amp;eacute;tait bien remplie. Petits d&amp;eacute;jeuners tr&amp;egrave;s copieux, je vous recommande le caf&amp;eacute;-cr&amp;ecirc;me et les g&amp;acirc;teaux maison. Nous n'avons pas test&amp;eacute; la table d'h&amp;ocirc;te, ce sera pour la prochaine fois car nous y retournerons &amp;agrave; coup s&amp;ucirc;r !&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Mich&amp;egrave;le - France - Avril 2022&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;Nous sommes venus s&amp;eacute;journer pour notre nuit de noces. Comment r&amp;eacute;sumer cet accueil ? Parfait !!! Les propri&amp;eacute;taires sont adorables, chaleureux, arrangeants et tout simplement pour notre nuit de noces on ne peut pas r&amp;ecirc;ver mieux.&amp;nbsp;&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Petit d&amp;eacute;jeuner au top, chambre magnifique, pr&amp;eacute;paratifs dans la chambre avec une propri&amp;eacute;taire arrangeante et soucieuse de notre bien &amp;ecirc;tre.&amp;nbsp;Merci merci !!!&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Faustine - France - Avril 2022&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;Superbe rencontre , merci beaucoup &amp;agrave; bient&amp;ocirc;t&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Damien - Belgique - Mars 2022&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;&lt;strong&gt;Accueil chaleureux et cadre tr&amp;egrave;s proven&amp;ccedil;al&lt;/strong&gt;.&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Chaleureux accueil &amp;agrave; la Villa Velleron par les nouveaux propri&amp;eacute;taires Sandra et Urs. L'endroit parfait pour un couple pour passer des vacances tranquilles dans le calme d'un village. Chambres et petits d&amp;eacute;jeuners bons. Malheureusement pas pu tester la table d'h&amp;ocirc;tes. &lt;/em&gt;&lt;br /&gt;&lt;em&gt;En &amp;eacute;t&amp;eacute;, il y a une jolie piscine. Dans le village de Velleron, il y a un march&amp;eacute; et plusieurs restaurants. Bon point de d&amp;eacute;part pour visiter la r&amp;eacute;gion du Lub&amp;eacute;ron et d'Avignon&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Florence - Suisse - Octobre 2021&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;Cadre coquet, cosy et accueillant en plein coeur du village, Sandra aux petits soins pour ses h&amp;ocirc;tes.&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Lydia - France - Octobre 2021&lt;span style=&quot;background-color: transparent;&quot;&gt;&amp;nbsp;&lt;/span&gt;&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;&lt;span style=&quot;background-color: transparent;&quot;&gt;Super endroit, surtout pour ceux qui cherchent &amp;agrave; visiter la Provence. C'est une belle villa, avec une charmante piscine, donc apr&amp;egrave;s une journ&amp;eacute;e d'excursions, c'est l'endroit id&amp;eacute;al pour se d&amp;eacute;tendre. N'oubliez pas de rester &amp;eacute;galement pour le d&amp;icirc;ner : 3 plats, avec d'excellentes entr&amp;eacute;es et &amp;agrave; base de produits locaux, sans oublier l'int&amp;eacute;ressante s&amp;eacute;lection de vins locaux ! Chacune des chambres dispose &amp;eacute;galement d'un int&amp;eacute;rieur individuel, dans un v&amp;eacute;ritable style &amp;eacute;prouv&amp;eacute;. Nous avons s&amp;eacute;journ&amp;eacute; dans la chambre Blue Blanc, qui &amp;eacute;tait vraiment spacieuse et avait m&amp;ecirc;me une baignoire.&lt;br /&gt;Les propri&amp;eacute;taires, Sandra et Urs, sont des h&amp;ocirc;tes accueillants, qui nous ont fourni toutes les informations pour vraiment profiter de notre voyage. M&amp;ecirc;me notre petit chien s'y sentait chez lui.&lt;br /&gt;Si vous voyagez en voiture, le garage peut &amp;ecirc;tre un peu &amp;eacute;troit, mais avec l'aide indispensable du propri&amp;eacute;taire, nous l'avons tr&amp;egrave;s bien g&amp;eacute;r&amp;eacute;.&lt;br /&gt;Je le recommande vraiment et nous reviendrions ici!&lt;br /&gt;&lt;br /&gt;Anna-Maria - France - Ao&amp;ucirc;t 2021&lt;/span&gt;&lt;/em&gt;&lt;/div&gt;";

$champ_2="&lt;div&gt;&lt;em&gt;Villa Velleron is the place to be, if you stay in that region. It&amp;rsquo;s the perfect starting point to explore Provence. I was given a warm welcome by Urs and Sandra, the host of Villa Velleron.&lt;br /&gt;&lt;br /&gt;Peter - Switzerland - June 2022&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;What a wonderful experience to spend a couple of days in this lovely place! Our only regret is that we didn't plan to spend longer. But that gives us a reason to plan to come again very soon. The accommodations were comfortable and the setting spectacular. But the best thing was the warmth of the hosts - sharing dinner and wine with like-minded people is always joyful. We will come again!&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Tim &amp;amp; Lisa - Williamsburg, VA - USA - May 2022&lt;/em&gt;&lt;/div&gt;";

$champ_3="&lt;div class=&quot;fpMxB MC _S b S6 H5 _a&quot; dir=&quot;ltr&quot; data-test-target=&quot;review-title&quot;&gt;&lt;em&gt;Ein Traum wurde wahr bei euch! Durch euch, diesen herrlichen Ort hier, die Gen&amp;uuml;sse und den Lavendel konnten wir die Provence mit vollen Sinnen geniessen. Merci beaucoup.&lt;br /&gt;&lt;br /&gt;Maik, Heike und Nelli - Deutschland - Juli 2022&lt;/em&gt;&lt;/div&gt;
&lt;div class=&quot;fpMxB MC _S b S6 H5 _a&quot; dir=&quot;ltr&quot; data-test-target=&quot;review-title&quot;&gt;&lt;em&gt;Wunderbare Tage in der Provence, feine kulinarische Empfehlungen in die n&amp;auml;here Umgebung. Einige einladende und erholsame &amp;Uuml;bernachtugen bei euch in der Villa Velleron. Wir sind verzaubert! Vielen Dank.&lt;br /&gt;&lt;br /&gt;Mich&amp;egrave;le, Bernhard und Marc - Schweiz - Juli 2022&lt;/em&gt;&lt;/div&gt;
&lt;div class=&quot;fpMxB MC _S b S6 H5 _a&quot; dir=&quot;ltr&quot; data-test-target=&quot;review-title&quot;&gt;&lt;em&gt;Vielen Dank f&amp;uuml;r die wundersch&amp;ouml;nen Tage in eurem traumhaften Paradies. Es war einfach perfekt! Komme gerne wieder.&lt;br /&gt;&lt;br /&gt;Tanja - Deutschland - Juli 2022&lt;/em&gt;&lt;/div&gt;
&lt;div class=&quot;fpMxB MC _S b S6 H5 _a&quot; dir=&quot;ltr&quot; data-test-target=&quot;review-title&quot;&gt;&lt;em&gt;Wir bedanken uns ganz herzlich, es war einfach super bei euch. Wir haben es sehr genossen und haben uns sehr wohl gef&amp;uuml;htl. W&amp;uuml;nschen euch alles Gute!&lt;br /&gt;&lt;br /&gt;Silvia &amp;amp; Kurt - Schweiz - Juni 2022&lt;/em&gt;&lt;/div&gt;
&lt;div class=&quot;fpMxB MC _S b S6 H5 _a&quot; dir=&quot;ltr&quot; data-test-target=&quot;review-title&quot;&gt;&lt;em&gt;Bl&amp;uuml;hender Lavendel. Die herrliche K&amp;uuml;hle der Gem&amp;auml;uer. Zikaden, die Zirpen, stahlblauer Himmel und w&amp;auml;rmende Sonne. Aprikosen. Eine fantastische Landschaft und ein herzliches Hotel inmitten eines intakten Dorfes. Danke f&amp;uuml;r den sch&amp;ouml;nen Aufenthalt.&lt;br /&gt;&lt;br /&gt;Madeleine &amp;amp; Simon - Schweiz - Juni 2022&lt;/em&gt;&lt;/div&gt;
&lt;div class=&quot;fpMxB MC _S b S6 H5 _a&quot; dir=&quot;ltr&quot; data-test-target=&quot;review-title&quot;&gt;&lt;em&gt;Herzlichen Dank f&amp;uuml;r den reizvollen Aufenthalt in Ihrem Haus. Wir haben uns wohl gef&amp;uuml;hlt und es war ein gelungener Auftakt unserer S&amp;uuml;dfrankreichreise.&lt;br /&gt;Herzlichst Ihre&lt;br /&gt;&lt;br /&gt;Karla, Lothar, Monika, Manfred - Deutschland - Juni 2022&lt;/em&gt;&lt;/div&gt;
&lt;div class=&quot;fpMxB MC _S b S6 H5 _a&quot; dir=&quot;ltr&quot; data-test-target=&quot;review-title&quot;&gt;&lt;em&gt;Uns hat es bei euch sehr gefallen, wir f&amp;uuml;hlten uns gut aufgehoben und waren richtig froh, in einem authentischen Ort und Umgebung wohnen zu d&amp;uuml;rfen.&amp;nbsp;Vielen Dank f&amp;uuml;r eure Gastfreundschaft und liebe Betreuung.&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Larissa, Alex, Svetlana, Iwan - Deutschland - Juni 2022&lt;/em&gt;&lt;/div&gt;
&lt;div class=&quot;fpMxB MC _S b S6 H5 _a&quot; dir=&quot;ltr&quot; data-test-target=&quot;review-title&quot;&gt;&lt;em&gt;Was ist das f&amp;uuml;r ein idyllisches Pl&amp;auml;tzchen mitten in der Provence! Wir f&amp;uuml;hlten uns wie zu Hause und und h&amp;auml;tten noch ganz lange bleiben k&amp;ouml;nnen. Die Liebe zum Detail ist &amp;uuml;berall zu sp&amp;uuml;ren. Herzlichen Dank f&amp;uuml;r die liebe Gastfreundschaft Sandra &amp;amp; Urs. Wir hoffen auf ein Wiederkommen - &amp;agrave; bient&amp;ocirc;t et bonne chance.&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Doris und Urs - Schweiz - Juni 2022&lt;/em&gt;&lt;/div&gt;
&lt;div class=&quot;fpMxB MC _S b S6 H5 _a&quot; dir=&quot;ltr&quot; data-test-target=&quot;review-title&quot;&gt;&lt;em&gt;Vielen lieben Dank f&amp;uuml;r den herzlichen Empfang! Mit viel Liebe zum Detail habt ihr dieses Haus gestaltet, zum Weiterempfehlen und Wiederkommen! Danke auch f&amp;uuml;r die guten Tipps f&amp;uuml;r Unternehmungen in der Umgebung.&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Eva und Frank - Deutschland - Juni 2022&lt;/em&gt;&lt;/div&gt;
&lt;div class=&quot;fpMxB MC _S b S6 H5 _a&quot; dir=&quot;ltr&quot; data-test-target=&quot;review-title&quot;&gt;&lt;em&gt;Liebe Sandra, lieber Urs&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Vielen Dank f&amp;uuml;r eure (Gast-) Freundschaft. Wir waren auch bei disem zweiten Besuch wieder begeistert von eurem &quot;H&amp;ouml;ckli&quot; hier in der Provence. Wir freuen uns auf ein Wiedersehen bei uns oder bei Euch.&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Susanne und Marco - Schweiz - Juni 2022&lt;/em&gt;&lt;/div&gt;
&lt;div class=&quot;fpMxB MC _S b S6 H5 _a&quot; dir=&quot;ltr&quot; data-test-target=&quot;review-title&quot;&gt;&lt;em&gt;&lt;em&gt;&lt;strong&gt;&lt;em&gt;&lt;em&gt;&lt;strong&gt;Kurzurlaub in Perfektion&lt;br /&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/em&gt;&lt;/em&gt;&lt;/strong&gt;&lt;em&gt;&lt;em&gt;Angereist aus der Schweiz mit dem Zug (bis Avignon), war unwesentlich l&amp;auml;nger als mit dem Auto. Per Mietauto von Avignon TGV gings zur Villa Velleron. Herzlicher Empfang, tolles Ambiente, feines Essen, Erholung am Pool, stilvolle Zimmer - genau so, wie es auf der Webseite zu sehen ist. Unz&amp;auml;hlige Ausflugsm&amp;ouml;glichkeiten und das provenzalische Flair machen die Villa Velleron zum 'Place-to-be'.&lt;br /&gt;&lt;br /&gt;&lt;/em&gt;&lt;/em&gt;&lt;em&gt;&lt;em&gt;Caroline und Hansruedi - Schweiz - Juni 2022&lt;/em&gt;&lt;/em&gt;&lt;/em&gt;&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;&lt;span style=&quot;background-color: transparent;&quot;&gt;&lt;em&gt;&lt;strong&gt;Ville Velleron - Das G&amp;auml;stehaus mit Charme und Ambiente&lt;/strong&gt;&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;Wir durften drei Tage in sch&amp;ouml;nster Umgebung verbringen. Wir haben das stilvolle Ambiente, die geschmackvollen Details und das wunderbare Fr&amp;uuml;hst&amp;uuml;ck aus vollen Z&amp;uuml;gen genossen.&lt;br /&gt;Noch passender h&amp;auml;tte man die Einrichtung nicht w&amp;auml;hlen k&amp;ouml;nnen! Von den M&amp;ouml;beln &amp;uuml;ber die Garten- und Poolanlage bis hin zum Geschirr und Tischset: &amp;uuml;berall ist die stilsichere Hand der Eigent&amp;uuml;mer zu erkennen.&lt;br /&gt;Wir k&amp;ouml;nnen die Villa Velleron allen anspruchsvollen Geniessern aus ganzem Herzen empfehlen.&lt;br /&gt;&lt;br /&gt;Susanne und Josef - Schweiz - Juni 2022&lt;/span&gt;&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;&lt;span style=&quot;background-color: transparent;&quot;&gt;Liebe Sandra, lieber Urs,&lt;br /&gt;ihr habt unsere Ferien zu einem unvergesslichen Erlebnis gemacht. Von Beginn an habt ihr uns durch euren herzlichen und warmherzigen Empfang wie Zuhause f&amp;uuml;hlen lassen. Vielen Dank f&amp;uuml;r die vielen tollen Tips zum Erkunden der Umgebun, die leckeren Table d'h&amp;ocirc;te und das wunderbare Ambiente. Ihr habt die Villa Velleron zu einem Juwel gemacht, zu dem man immer wieder gerne kommt.&lt;br /&gt;Merci beaucoup et &amp;agrave; bient&amp;ocirc;t&lt;br /&gt;&lt;br /&gt;Dagmar und Ralph - Schweiz - Mai 2022&lt;/span&gt;&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;&lt;span style=&quot;background-color: transparent;&quot;&gt;Wir haben uns hier sehr wohl gef&amp;uuml;hlt. Das ganze Objekt ist toll und das Fr&amp;uuml;hst&amp;uuml;ck sehr fein. Das gemeinsame Abendessen hat uns gut gefallen. Die herzliche Atmosph&amp;auml;re durch unsere Gastgeber rundete das Urlaubserlebnis ab. Sehr zu empfehlen!&lt;br /&gt;&lt;br /&gt;Monika, Elko und Ronny - Deutschland - Mai 2022&lt;/span&gt;&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;&lt;span style=&quot;background-color: transparent;&quot;&gt;Wir wollten&amp;nbsp;einige Tage in der Region von Avignon verbringen. Die &amp;bdquo;Villa Velleron&amp;ldquo; hat sich als der ideale Ausgangspunkt erwiesen. Zur&amp;uuml;ck von unser Tour konnten wir das Ambiente, mit seinen liebevollen Details, auf uns wirken lassen. Der historische Bau, das s&amp;uuml;dfranz&amp;ouml;sische, grossz&amp;uuml;gige Zimmer, der Innenhof mit unterschiedlichsten Ruhezonen und der beheizte Pool haben uns sehr gefallen.&amp;nbsp;&lt;br /&gt;&lt;/span&gt;Sandra &amp;amp; Urs sind &amp;uuml;beraus aufmerksame Gastgeber die im Hintergrund &amp;bdquo;perfekt/schweizerisch&amp;ldquo; f&amp;uuml;r unser Wohl sorgten.&lt;/em&gt;&lt;br /&gt;&lt;em&gt;&lt;span style=&quot;background-color: transparent;&quot;&gt;Beim leckeren Fr&amp;uuml;hst&amp;uuml;ck ein kurzer Austausch oder Tipp zum geplanten Tagesausflug.&lt;br /&gt;&lt;/span&gt;&lt;span style=&quot;background-color: transparent;&quot;&gt;Die genutzte Gelegenheit am Donnerstag und Freitag das Abendessen jeweils im Innenhof bzw. im Esszimmer zu buchen war absolut richtig. Mit den Lebensmitteln vom Bauernmarkt in Velleron zauberte Sandra in der kleinen K&amp;uuml;che ein 15 Punkte-Men&amp;uuml;.&lt;br /&gt;&lt;/span&gt;Danke! Wir kommen bestimmt wieder.&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;&lt;span style=&quot;background-color: transparent;&quot;&gt;Margrit &amp;amp; Manfred - Schweiz - April 2022&lt;/span&gt;&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;&lt;strong&gt;&lt;strong&gt;Erholung pur in der Provence&lt;/strong&gt;&lt;br /&gt;&lt;br /&gt;&lt;/strong&gt;Die Villa Velleron, ein idealer Ausgangspunkt, um die Provence zu entdecken. Mit viel Charme und Herzlichkeit wurden wir von den Gastgebern Sandra und Urs empfangen. Die beiden haben die Villa Velleron mit viel Liebe zum Detail eingerichtet. Der Garten, eine Oase inmitten des franz&amp;ouml;sischen St&amp;auml;dtchens: Schattige Orte zwischen Lavendel, Kr&amp;auml;utern und Oliven, Abk&amp;uuml;hlung am Pool oder lauschige Pl&amp;auml;tzchen in den verschiedenen Winkeln des Innenhofes. Wir sch&amp;auml;tzten das grossz&amp;uuml;gige Zimmer mit dem modernen Bad, das excellente Essen beim &quot;Table d'h&amp;ocirc;te&quot; , den gem&amp;uuml;tlichen Austausch mit den Gastgebern und die vielseitige Beratung, sei es f&amp;uuml;r Ausflugsideen oder Restaurantempfehlungen. Gerne kommen wir wieder und k&amp;ouml;nnen die Villa Velleron w&amp;auml;rmstens empfehlen.&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Regula - Schweiz - Oktober 2021&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;&lt;strong&gt;&lt;strong&gt;Villa Velleron - es war einfach perfekt !&lt;/strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Die Tage in Velleron waren eines meiner pers&amp;ouml;nliches Highlights im 2021.&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Mein Zimmer hatte viel Charme und ich fand mit der Villa Velleron eine Oase der Ruhe und Entspannung mit Pool.&amp;nbsp;Das franz&amp;ouml;sische Fr&amp;uuml;hst&amp;uuml;ck mit Kaffee am Tisch im Innenhof war der perfekte Start in den neuen Tag.&amp;nbsp;Beim Abendessen durfte ich Sandra's Kochk&amp;uuml;nste in wunderbarer Umgebung und Gesellschaft geniessen.&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Velleron mit Bauernmarkt liegt sehr zentral f&amp;uuml;r Ausfl&amp;uuml;ge und Aktivit&amp;auml;ten in der Provence. Es gibt so viel mehr zu sehen als mir in den wenigen Tagen m&amp;ouml;glich war.&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Ich besuchte unter anderem die Luberon D&amp;ouml;rfer, L&amp;rsquo;Isle sur la Sorgue und Saint Remy de Provence.&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Einen herzlichen Dank an die aufmerksamen &amp;amp; freundlichen Gastgeber.&lt;/em&gt;&lt;br /&gt;&lt;em&gt;PS: Beim n&amp;auml;chsten mal komme ich in Begleitung meiner Frau.&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Manfred - Schweiz - September 2021&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;&lt;strong&gt;Mit neuen Gastgebern&lt;br /&gt;&lt;br /&gt;&lt;/strong&gt;Wir waren zu viert eine Woche bei Sandra und Urs, die das Anwesen 2021 &amp;uuml;bernommen haben. Es war einfach herrlich! Die sch&amp;ouml;nen Zimmer, das friedliche Fr&amp;uuml;hst&amp;uuml;ck im Innenhof, die famili&amp;auml;re Atmosph&amp;auml;re, das einzigartige Abendessen mit den anderen G&amp;auml;sten, die hilfreichen Ausflugstipps und der blaue Pool machten den Aufenthalt zu dem was man sich unter Ferien vorstellt.&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Susanne - Schweiz - September 2021&lt;/em&gt;&lt;/div&gt;
&lt;div&gt;&lt;em&gt;&lt;strong&gt;Sommeraufenthalt in der Villa Velleron&lt;br /&gt;&lt;/strong&gt;&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Zu unseren Sommerferien wurden wir herzlich in der Villa Velleron empfangen.&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Das Ambiente ist mit liebe zum Detail eingerichtet und l&amp;auml;dt zum verweilen ein.&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Ausserdem sind die Gastgeber Sandra und Urs sehr freundlich, hilfbereit und geben hervorragende Tipps f&amp;uuml;r abwechlungsreiche Tagesausfl&amp;uuml;ge.&lt;/em&gt;&lt;br /&gt;&lt;em&gt;Wir freuen uns bereits auf den n&amp;auml;chsten Aufenthalt in der Villa Velleron.&lt;/em&gt;&lt;br /&gt;&lt;br /&gt;&lt;em&gt;Cyrill &amp;amp; Mich&amp;egrave;le - Schweiz - Juli 2021&lt;/em&gt;&lt;/div&gt;";

$champ_4="";

$champ_5="";

$champ_6="";

$champ_7="";

$champ_8="";

$champ_9="";

$champ_10="";

$champ_11="";

$champ_12="";

$champ_13="";

$champ_14="";

$champ_15="";

$champ_16="";

$champ_17="";

$champ_18="";

$champ_19="";

$champ_20="";

?>
