<?
/* Ce fichier contient les parametres de la page a afficher */

/*************************/
/* champs pour affichage */
/*************************/

$champ_1="&lt;p&gt;&lt;em&gt;La Villa Velleron est ouvert toute l'ann&amp;eacute;e. Prix pour 2022.&lt;/em&gt;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr style=&quot;background: #e5e6e6fd;&quot;&gt;
&lt;td valign=&quot;top&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;td valign=&quot;top&quot;&gt;
&lt;p&gt;&lt;strong&gt;Basse&amp;nbsp;saison&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;janvier - mars&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;novembre - d&amp;eacute;cembre&lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;(sans jours f&amp;eacute;ri&amp;eacute;s)&lt;/span&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td valign=&quot;top&quot;&gt;
&lt;p&gt;&lt;strong&gt;Moyenne&amp;nbsp;saison&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;avril - juin&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;septembre - octobre&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;(sans jours f&amp;eacute;ri&amp;eacute;s)&lt;/span&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td valign=&quot;top&quot;&gt;
&lt;p&gt;&lt;strong&gt;Haute&amp;nbsp;saison&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;juillet - ao&amp;ucirc;t&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;(et&amp;nbsp;jours f&amp;eacute;ri&amp;eacute;s)&lt;/span&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;strong&gt;Chambres &quot;Confort&quot; dans le b&amp;acirc;timent annexe&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Chaque chambre dispose d'une terrasse commune &amp;agrave; deux chambres&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Chambre Mezzanine&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;115 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;td&gt;135 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Chambre Bleu &amp;amp; Blanc&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;115 &amp;euro;&lt;/td&gt;
&lt;td&gt;135 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;strong&gt;Chambres &quot;Tradition&quot; dans la maison principale&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Ces chambres ne disposent pas de possibilit&amp;eacute; de prendre des repas de fa&amp;ccedil;on autonome&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Chambre Luberon&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;95 &amp;euro;&lt;/td&gt;
&lt;td&gt;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;125 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Chambre Lou Soleil&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;95 &amp;euro;&lt;/td&gt;
&lt;td&gt;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;125 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Suite Naturelle&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;110 &amp;euro;&lt;/td&gt;
&lt;td&gt;120 &amp;euro;&lt;/td&gt;
&lt;td&gt;140 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;em&gt;Les prix des chambres s'entendent en &amp;euro; par nuit pour 1 ou 2 personnes, petit-déjeuner offert.&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;Personne suppl&amp;eacute;mentaire (à partir de 2 ans) dans la même chambre : 25 &amp;euro; par nuit, petit-déjeuner offert &amp;ndash; uniquement Suite Naturelle (max. 2 personnes suppl&amp;eacute;mentaires)&lt;br /&gt;et Mezzanine (max. 1 personne suppl&amp;eacute;mentaire).&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;Forfait pour enfant de moins de 2 ans : 20 &amp;euro; (mise à disposition d&amp;rsquo;un lit parapluie compris).&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;G&amp;icirc;te Jasmin&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;770 &amp;euro; / semaine&lt;/td&gt;
&lt;td&gt;840 &amp;euro; / semaine&lt;/td&gt;
&lt;td&gt;980 &amp;euro; / semaine&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;strong&gt;G&amp;icirc;te &amp;ndash; Studio de vacances dans le b&amp;acirc;timent annexe&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;La g&amp;icirc;te est lou&amp;eacute; par semaine du samedi au samedi, du mai au septembre. Octobre &amp;agrave; avril, la dur&amp;eacute;e minimale du s&amp;eacute;jour est de 3 nuits.&lt;br /&gt;H&amp;eacute;bergement en self-catering.&lt;br /&gt;&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;L&lt;em&gt;es prix du g&amp;icirc;te s'entendent pour 2 personnes par semaine, linge de lit, de bain et de cuisine et nettoyage final compris.&amp;nbsp;Prix pour des s&amp;eacute;jours de 3 nuits sur demande.&lt;/em&gt;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div id=&quot;cgv&quot;&gt;
&lt;h4&gt;Conditions g&amp;eacute;n&amp;eacute;rales de vente:&lt;/h4&gt;
&lt;ul&gt;
&lt;li&gt;La r&amp;eacute;servation viendra effective lors de l'encaissement d'un acompte de 25% dans les 7 jours suivant la date de la confirmation.&lt;/li&gt;
&lt;li&gt;Conditions d'annulation :&lt;br /&gt;L'acompte est non-remboursable.&lt;br /&gt;Pour une annulation faite jusqu'&amp;agrave; 29 jours avant la date de l'arriv&amp;eacute;e, l'acompte pourra &amp;ecirc;tre transf&amp;eacute;r&amp;eacute; pour un autre s&amp;eacute;jour pendant les 12 mois suivant la date d'annulation.&lt;br /&gt;Pour une annulation faite entre 28 et 15 jours avant la date de l'arriv&amp;eacute;e, l'acompte reste acquis aux propri&amp;eacute;taires.&lt;br /&gt;Si l'annulation intervient moins de 15 jours avant la date de l'arriv&amp;eacute;e, facturation de 100% du prix du s&amp;eacute;jour (pareil pour les no-show).&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/li&gt;
&lt;li&gt;Veuillez vous informer aupr&amp;egrave;s de votre assureur concernant une assurance annulation.&lt;/li&gt;
&lt;li&gt;Modes de r&amp;egrave;glement:&amp;nbsp;Par virement bancaire ou en esp&amp;egrave;ces. Les ch&amp;egrave;que bancaire fran&amp;ccedil;ais, ch&amp;egrave;que-vacances ANCV ne sont pas accept&amp;eacute;s.&lt;/li&gt;
&lt;li&gt;Sous r&amp;eacute;serve de modification des prix.&lt;/li&gt;
&lt;li&gt;Horaires d'arriv&amp;eacute;e et de d&amp;eacute;part:&lt;br /&gt;accueil entre 16h et 18h le jour de l'arriv&amp;eacute;e,&lt;br /&gt;chambres &amp;agrave; lib&amp;eacute;rer avant 10h le jour du d&amp;eacute;part.&lt;/li&gt;
&lt;li&gt;Petit-d&amp;eacute;jeuner entre 8h00 et 9h30.&lt;/li&gt;
&lt;li&gt;Horaires et r&amp;egrave;gles de la piscine:&lt;br /&gt;entre 08h00 et 19h00, en respectant les r&amp;egrave;gles de bon voisinage (pas de jeux bruyants).&lt;br /&gt;Bien que la piscine corresponde aux normes de s&amp;eacute;curit&amp;eacute;, nous demandons une surveillance permanente des enfants par les parents.&lt;/li&gt;
&lt;li&gt;La r&amp;eacute;servation n'est valable que pour les personnes y figurant.&lt;/li&gt;
&lt;li&gt;La Villa Velleron est une b&amp;acirc;tisse historique et peut pr&amp;eacute;senter des dangers pour les petits enfants. Certaines terrasses sont sans balustrades, la piscine, le jardin en terrasses et des anciens escaliers pr&amp;eacute;sentent des risques n&amp;eacute;cessitant une surveillance par les parents.&lt;/li&gt;
&lt;/ul&gt;
&lt;/div&gt;
&lt;p&gt;&lt;em&gt;Mars 2022.&lt;/em&gt;&lt;/p&gt;";

$champ_2="&lt;p&gt;&lt;em&gt;The Villa Velleron is open all year round.&lt;/em&gt;&lt;em&gt;&amp;nbsp;Prices for 2022.&lt;/em&gt;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr style=&quot;background: #e5e6e6fd;&quot;&gt;
&lt;td valign=&quot;top&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;td valign=&quot;top&quot;&gt;
&lt;p&gt;&lt;strong&gt;Low&amp;nbsp;season&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;January - March &lt;br /&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;November - December&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;(without holidays)&lt;/span&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td valign=&quot;top&quot;&gt;
&lt;p&gt;&lt;strong&gt;Mid&amp;nbsp;season&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;April - June&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;September - October&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;(without holidays)&lt;/span&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td valign=&quot;top&quot;&gt;
&lt;p&gt;&lt;strong&gt;High&amp;nbsp;season&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;July - August&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;(and holidays)&lt;/span&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;strong&gt;&quot;Comfort&quot; rooms in the annex building&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;These rooms each share a private terrace&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Room Mezzanine&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;115 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;td&gt;135 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Room Bleu &amp;amp; Blanc&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;115 &amp;euro;&lt;/td&gt;
&lt;td&gt;135 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;strong&gt;&quot;Tradition&quot; rooms in the main house&amp;nbsp;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;These rooms have no facilities for preparing or consuming meals&amp;nbsp;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Room Luberon&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;95 &amp;euro;&lt;/td&gt;
&lt;td&gt;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;125 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Room Lou Soleil&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;95 &amp;euro;&lt;/td&gt;
&lt;td&gt;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;125 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Suite Naturelle&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;110 &amp;euro;&lt;/td&gt;
&lt;td&gt;120 &amp;euro;&lt;/td&gt;
&lt;td&gt;140 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;em&gt;Room rates are in &amp;euro; per night for occupancy by 1 or 2 persons, breakfast offered.&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;Additional person (2 years or older) in the same room : 25 &amp;euro; per night, breakfast offered &amp;ndash; possible only in Suite Naturelle (max. 2 additional persons)&lt;/em&gt;&lt;em&gt;&lt;br /&gt; &lt;em&gt;and Mezzanine (max. 1 additional person).&lt;/em&gt;&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;Flat-rate add-on for children under 2 years : 20 &amp;euro; (folding bed available).&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;G&amp;icirc;te Jasmin&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;770 &amp;euro;&lt;/td&gt;
&lt;td&gt;840 &amp;euro;&lt;/td&gt;
&lt;td&gt;980 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;strong&gt;&lt;span style=&quot;font-size: 8.5pt; font-family: 'Verdana',sans-serif; color: #787878;&quot;&gt;G&amp;icirc;te &amp;ndash; Studio in the annexe building&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p style=&quot;font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;&quot;&gt;&lt;em&gt;&lt;span style=&quot;font-size: 8.5pt; font-family: 'Verdana',sans-serif; color: #787878;&quot;&gt;The studio is rented per week from Saturday to Saturday from mai to september. From october to april, the minimum stay is 3 nights.&lt;/span&gt;&lt;/em&gt;&lt;em&gt;&lt;span style=&quot;font-size: 8.5pt; font-family: 'Verdana',sans-serif; color: #787878;&quot;&gt;&lt;br /&gt; &lt;em&gt;&lt;span style=&quot;font-family: 'Verdana',sans-serif;&quot;&gt;Self-catering accommodation.&lt;/span&gt;&lt;/em&gt;&lt;/span&gt;&lt;/em&gt;&lt;/p&gt;
&lt;p style=&quot;font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;&quot;&gt;&lt;em&gt;&lt;span style=&quot;font-size: 8.5pt; font-family: 'Verdana',sans-serif; color: #787878;&quot;&gt;Prices for the g&amp;icirc;te are for 2 people per week, bed-, bath- and kitchen-linen and final cleaning included.&amp;nbsp;Prices for stays of 3 nights on request.&lt;/span&gt;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div id=&quot;cgv&quot;&gt;
&lt;h4&gt;General Terms &amp;amp; Conditions :&lt;/h4&gt;
&lt;ul&gt;
&lt;li&gt;The reservation becomes effective upon receipt of a deposit payment of 25% of the rental price within 7 days after the confirmation date.&lt;/li&gt;
&lt;li&gt;Cancellation terms:&lt;br /&gt;The deposit amount is nonrefundable.&lt;br /&gt;In case of cancellation up to 29 days before the scheduled arrival, the deposit may be used for another holiday within 12 months following the cancellation date.&lt;br /&gt;In case of cancellation between 28 and 15&amp;nbsp;days before the scheduled arrival, the deposit will remain with the owner.&lt;br /&gt;In case of cancellation 14 or less days before the scheduled arrival, no show or early departure, the total lodging cost will be due. We recommend to take out travel cancellation cost insurance - please contact your insurance broker.&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/li&gt;
&lt;li&gt;Payment conditions : By bank transfer or in cash on site. No cheques accepted.&lt;/li&gt;
&lt;li&gt;Prices are subject to change&lt;/li&gt;
&lt;li&gt;Arrival and departure:&lt;br /&gt;we are happy to welcome you on your arrival date between 4:00pm and 6:00pm,&lt;br /&gt;rooms have to be cleared by 10:00am at the latest on the day of depart.&lt;/li&gt;
&lt;li&gt;Breakfast from 8:00am to 9:30am.&lt;/li&gt;
&lt;li&gt;Pool hours and rules:&lt;br /&gt;from 8:00am to 7:00pm, respecting the neighborhood (noise control).&lt;br /&gt;Although the pool is secured corresponding to the French law requirements, we ask parents to supervise their children at any time.&lt;/li&gt;
&lt;li&gt;The reservation is valid only for the announced persons.&lt;/li&gt;
&lt;li&gt;Villa Velleron is a historic building and can pose certain risk to smaller children: terraces with low railings, the pool, the terraced garden and staircases require non-stop surveillance by the parents.&lt;/li&gt;
&lt;/ul&gt;
&lt;/div&gt;
&lt;p&gt;&lt;em&gt;&lt;em&gt;March&amp;nbsp;&lt;/em&gt;2022.&lt;/em&gt;&lt;/p&gt;";

$champ_3="&lt;p&gt;&lt;em&gt;&amp;nbsp;Die Villa Velleron ist ganzj&amp;auml;hrig ge&amp;ouml;ffnet. Preise 2022.&lt;/em&gt;&lt;/p&gt;
&lt;table&gt;
&lt;tbody&gt;
&lt;tr style=&quot;background: #e5e6e6fd;&quot;&gt;
&lt;td valign=&quot;top&quot;&gt;&amp;nbsp;&lt;/td&gt;
&lt;td valign=&quot;top&quot;&gt;
&lt;p&gt;&lt;strong&gt;Nebensaison&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;Januar - M&amp;auml;rz&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;November - Dezember&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;(ohne Feiertage)&lt;/span&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td valign=&quot;top&quot;&gt;
&lt;p&gt;&lt;strong&gt;Zwischensaison&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;April - Juni&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;September - Oktober&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;(ohne Feiertage)&lt;/span&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;td valign=&quot;top&quot;&gt;
&lt;p&gt;&lt;strong&gt;Hochsaison&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;Juli - August&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span style=&quot;font-size: 10pt;&quot;&gt;(und Feiertage)&lt;/span&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;strong&gt;Zimmer &quot;Comfort&quot; im Anbau&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Diese Zimmer teilen sich eine private Terrasse&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Zimmer Mezzanine&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;115 &amp;euro;&amp;nbsp;&lt;/td&gt;
&lt;td&gt;135 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Zimmer Bleu &amp;amp; Blanc&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;&amp;nbsp;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;115 &amp;euro;&lt;/td&gt;
&lt;td&gt;135 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;strong&gt;Zimmer &quot;Tradition&quot; im Haupthaus&amp;nbsp;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;Diese Zimmer haben keine M&amp;ouml;glichkeit zur Zubereitung oder Einnahme von Mahlzeiten&amp;nbsp;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Zimmer Luberon&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;95 &amp;euro;&lt;/td&gt;
&lt;td&gt;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;125 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Zimmer Lou Solei&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;95 &amp;euro;&lt;/td&gt;
&lt;td&gt;105 &amp;euro;&lt;/td&gt;
&lt;td&gt;125 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;Suite Naturelle&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;110 &amp;euro;&lt;/td&gt;
&lt;td&gt;120 &amp;euro;&lt;/td&gt;
&lt;td&gt;140 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;em&gt;Die Zimmerpreise verstehen sich in &amp;euro; pro Nacht und f&amp;uuml;r eine Belegung mit 1 - 2 Personen, Fr&amp;uuml;hst&amp;uuml;ck offeriert.&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;Zus&amp;auml;tzliche Person (ab 2 Jahren) im selben Zimmer : 25 &amp;euro; pro Nacht, Fr&amp;uuml;hst&amp;uuml;ck offeriert &amp;ndash; nur in der Suite Naturelle (max. 2 Zusatzpersonen)&lt;br /&gt;und im Mezzanine (max. 1 Zusatzperson).&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;&lt;em&gt;Einmaliger Zuschlag von 20 &amp;euro; f&amp;uuml;r Kinder unter 2 Jahren (Zurverf&amp;uuml;gungstellung eines Kleinkind-Faltbettes m&amp;ouml;glich).&lt;/em&gt;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td&gt;
&lt;p&gt;G&amp;icirc;te Jasmin&lt;/p&gt;
&lt;/td&gt;
&lt;td&gt;770 &amp;euro;&lt;/td&gt;
&lt;td&gt;840 &amp;euro;&lt;/td&gt;
&lt;td&gt;980 &amp;euro;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style=&quot;background: #c0cdfffd;&quot; colspan=&quot;4&quot;&gt;
&lt;p&gt;&lt;strong&gt;G&amp;icirc;te &amp;ndash; Studio im Nebengeb&amp;auml;ude&lt;br /&gt;&lt;/strong&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;Die Unterkunft wird von Mai bis September pro Woche von Samstag bis Samstag vermietet. Von Oktober bis April betr&amp;auml;gt die Mindestaufenthaltsdauer 3 N&amp;auml;chte.&lt;br /&gt;Selbstversorgerunterkunft.&lt;br /&gt;&lt;/em&gt;&lt;/p&gt;
&lt;p&gt;&lt;em&gt;&lt;em&gt;Die Preise f&amp;uuml;r das G&amp;icirc;te verstehen sich f&amp;uuml;r 2 Personen pro Woche, Bett-, Bad- und K&amp;uuml;chenw&amp;auml;sche sowie Endreinigung inbegriffen.&amp;nbsp;Preise f&amp;uuml;r Aufenthalte von 3 N&amp;auml;chten auf Anfrage.&lt;/em&gt;&lt;/em&gt;&lt;/p&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;/table&gt;
&lt;div id=&quot;cgv&quot;&gt;
&lt;h4&gt;Allgemeine Gesch&amp;auml;ftsbedingungen :&lt;/h4&gt;
&lt;ul&gt;
&lt;li&gt;Eine Reservierung gilt als best&amp;auml;tigt bei Erhalt einer Anzahlung&lt;strong&gt;&amp;nbsp;&lt;/strong&gt;in H&amp;ouml;he von 25% innerhalb 7 Tagen ab Datum der Reservierungsbest&amp;auml;tigung.&lt;/li&gt;
&lt;li&gt;Stornobedingungen:&lt;br /&gt;Die Anzahlung ist nicht r&amp;uuml;ckerstattbar.&lt;br /&gt;Bei Storno bis 29 Tage vor dem Ankunftsdatum wird die Anzahlung einbehalten, Sie k&amp;ouml;nnen sie einmalig auf einen anderen Aufenthalt innerhalb bis zu 12 Monaten &amp;uuml;bertragen.&lt;br /&gt;Bei Storno 28 bis 15 Tage vor dem Ankunftsdatum wird die Anzahlung einbehalten.&lt;br /&gt;Bei Storno ab 14 Tage vor dem Ankunftsdatum, ebenso wie f&amp;uuml;r nicht angetretene oder vorzeitig abgebrochene Aufenthalte&amp;nbsp;wird der Gesamtpreis f&amp;uuml;r den gesamten reservierten Aufenthalt in Rechnung gestellt. Wir empfehlen Ihnen den Abschluss einer Reiser&amp;uuml;cktrittskostenversicherung - bitte kontaktieren Sie dazu den Versicherungspartner Ihres Vertrauens.&lt;strong&gt;&lt;br /&gt;&lt;/strong&gt;&lt;/li&gt;
&lt;li&gt;Akzeptierte Zahlungsmittel: Per Bank&amp;uuml;berweisung oder bar vor Ort.&amp;nbsp;Wir akzeptieren keine Reisechecks.&lt;/li&gt;
&lt;li&gt;Preis&amp;auml;nderungen vorbehalten.&lt;/li&gt;
&lt;li&gt;Ankunft und Abreise:&lt;br /&gt;Wir empfangen Sie am Anreisetag zwischen 16:00 und 18:00 Uhr.&lt;br /&gt;Freigabe des Zimmers am Abreisetag bis sp&amp;auml;testens 10:00 Uhr.&lt;/li&gt;
&lt;li&gt;Fr&amp;uuml;hst&amp;uuml;ck zwischen 8:00 Uhr und 9:30 Uhr.&lt;/li&gt;
&lt;li&gt;Pool - Zeiten und Regeln:&lt;br /&gt;zwischen 08:00 Uhr und 19:00 Uhr, bitte respekteiren Sie die Nachbarschaft und die anderen G&amp;auml;ste.&lt;br /&gt;Obwohl der Pool entsprechend der franz&amp;ouml;sischen Normen gesichert ist, bitten wir Eltern um durchgehende Beaufsichtigung ihrer Kinder.&lt;/li&gt;
&lt;li&gt;Die Reservierung ist nur f&amp;uuml;r die angemeldeten Personen g&amp;uuml;ltig.&amp;nbsp;&lt;/li&gt;
&lt;li&gt;Die Villa Velleron ist ein historisches Geb&amp;auml;ude und kann f&amp;uuml;r &lt;strong&gt;j&amp;uuml;ngere Kinder&lt;/strong&gt; gewisse Risiken darstellen: Balkone mit niedrigen Gel&amp;auml;ndern, das Schwimmbad, der in Terrassen angelegte Garten sowie Treppen mit unregelm&amp;auml;&amp;szlig;igen Stufen erfordern eine durchg&amp;auml;ngige Aufsicht durch die Eltern.&lt;/li&gt;
&lt;/ul&gt;
&lt;/div&gt;
&lt;p&gt;&lt;em&gt;M&amp;auml;rz 2022.&lt;/em&gt;&lt;/p&gt;";

$champ_4="";

$champ_5="";

$champ_6="";

$champ_7="";

$champ_8="";

$champ_9="";

$champ_10="";

$champ_11="";

$champ_12="";

$champ_13="";

$champ_14="";

$champ_15="";

$champ_16="";

$champ_17="";

$champ_18="";

$champ_19="";

$champ_20="";

?>
