<?
/* Ce fichier contient les parametres de la page a afficher */

/*************************/
/* champs pour affichage */
/*************************/

$champ_1="&lt;div class=&quot;offres&quot;&gt;
&lt;div&gt;
&lt;h3&gt;La Provence en bref&lt;/h3&gt;
&lt;a href=&quot;photos/Tourisme-carte.jpg&quot; data-lightbox=&quot;Provence&quot; data-title=&quot;La Provence &amp;agrave; la carte @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/Tourisme-carte.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Velleron est situ&amp;eacute; au centre des principales curiosit&amp;eacute;s de la Provence :&lt;/p&gt;
&lt;p&gt;D'Orange au nord &amp;agrave; la Camargue au sud, des c&amp;eacute;l&amp;egrave;bres champs de lavande &amp;agrave; l'est au Pont du Gard &amp;agrave; l'ouest.&lt;/p&gt;
&lt;p&gt;Une s&amp;eacute;lection de villages de Provence officiellement class&amp;eacute;s &quot;Plus Beaux Villages de France&quot; :&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;Gordes&lt;/li&gt;
&lt;li&gt;Abbaye de S&amp;eacute;nanque&lt;/li&gt;
&lt;li&gt;Village des Bories&lt;/li&gt;
&lt;li&gt;M&amp;eacute;nerbes&lt;/li&gt;
&lt;li&gt;Roussillon&lt;/li&gt;
&lt;/ul&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Art, culture &amp;amp; histoire&lt;/h3&gt;
&lt;img src=&quot;photos/provence-aix.jpg&quot; alt=&quot;&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Aix-en-Provence&amp;nbsp;; Paul C&amp;eacute;zanne, Sainte-Victoire, 1h30 Arles&amp;nbsp;; Amphith&amp;eacute;&amp;acirc;tre, LUMA 1h15&lt;/p&gt;
&lt;p&gt;Avignon&amp;nbsp;; Pont Saint-Benezet, Festival, Palais des papes 30 min&lt;/p&gt;
&lt;p&gt;Baux &amp;amp; Les Carri&amp;egrave;res de Lumi&amp;egrave;re&amp;nbsp;; 50 min&lt;/p&gt;
&lt;p&gt;Bonnieux&amp;nbsp;; Pont Julien, 30 min&lt;/p&gt;
&lt;p&gt;Gordes&amp;nbsp;; Ch&amp;acirc;teau, Villages des Bories, Abbaye de S&amp;eacute;nanque 30 min&lt;/p&gt;
&lt;p&gt;Lacoste&amp;nbsp;; Ch&amp;acirc;teau et Village, 40 min&lt;/p&gt;
&lt;p&gt;Les Baux de Provence; Les Carri&amp;egrave;res de Lumi&amp;egrave;re, 1h&lt;/p&gt;
&lt;p&gt;Lourmarin&amp;nbsp;; Ch&amp;acirc;teau et Village, 50 min&lt;/p&gt;
&lt;p&gt;Orange; Th&amp;eacute;&amp;acirc;tre antique 40 min&lt;/p&gt;
&lt;p&gt;Pont du Gard, Ar&amp;egrave;ne de N&amp;icirc;mes 1h15&lt;/p&gt;
&lt;p&gt;Saint-Remy de Provence&amp;nbsp;; Vincent van Gogh, Ville romaine Glanum 35 min&lt;/p&gt;
&lt;p&gt;Uz&amp;egrave;s&amp;nbsp;; Village et Mus&amp;eacute;e Georges Borias, 50 min&lt;/p&gt;
&lt;p&gt;Vaison-la-Romaine&amp;nbsp;; fouilles romaines, 50 min&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;La Provence au bord de la mer&lt;/h3&gt;
&lt;img src=&quot;photos/provence-mer.jpg&quot; alt=&quot;&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Camargue, Parc naturel r&amp;eacute;gional, Aigues-Mortes 1h30&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;C&amp;ocirc;te Bleue 1h&lt;/p&gt;
&lt;p&gt;Calanques et Cassis 1h30&lt;/p&gt;
&lt;p&gt;Saintes-Maries de la mer 1h30&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Marseille, Vieux port, la Bonne M&amp;egrave;re, 1h30&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;R&amp;eacute;gions &amp;amp; Parcs naturels, Mont Ventoux&lt;/h3&gt;
&lt;img src=&quot;photos/provence-ventoux.jpg&quot; alt=&quot;Mont Ventoux&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Alpilles - Parc naturel r&amp;eacute;gional&amp;nbsp;;&lt;/p&gt;
&lt;p&gt;Saint-Remy-de Provence, Les Baux de Provence&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Avignon et Ch&amp;acirc;teauneuf-du-Pape&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;C&amp;ocirc;te du Rh&amp;ocirc;ne&amp;nbsp;;&lt;/p&gt;
&lt;p&gt;H&amp;eacute;ritage culturel romain et r&amp;eacute;gion viticole, Orange&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Luberon;&lt;/p&gt;
&lt;p&gt;Bonnieux, Cavaillon, Cheval-Blanc, Gordes, Lacoste, Lauris, Les Taillades, Lourmarin, Maubec, M&amp;eacute;nerbes, M&amp;eacute;rindol, Opp&amp;egrave;de, Puget-sur-Durance, Puyvert, Robion, Roussillon (les Ocres de Roussillon)&lt;/p&gt;
&lt;p&gt;Rustrel;&lt;/p&gt;
&lt;p&gt;Colorado Proven&amp;ccedil;al&lt;/p&gt;
&lt;p&gt;Vall&amp;eacute;e de la Sorgue;&amp;nbsp;;&lt;/p&gt;
&lt;p&gt;L&amp;rsquo;Isle-sur-la-Sorgue&lt;/p&gt;
&lt;p&gt;Ventoux&amp;nbsp;;&lt;br /&gt; Mont Ventoux, B&amp;eacute;doin, Mazan, Mormoiron, Les gorges de la Nesque&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;March&amp;eacute;s&lt;/h3&gt;
&lt;img src=&quot;photos/provence-marche.jpg&quot; alt=&quot;&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Lundi : B&amp;eacute;doin, Cavaillon, St-Didier&lt;/p&gt;
&lt;p&gt;Mardi : Gordes, Vaison la Romaine, t. Saturnin-les-Apt, Aix-en-Provence&lt;/p&gt;
&lt;p&gt;Mercredi : Saint Remy de Provence&lt;/p&gt;
&lt;p&gt;Jeudi : Aix en Provence, L&amp;rsquo;Isle sur la Sorgue&lt;/p&gt;
&lt;p&gt;Vendredi : Carpentras, Lourmarin&lt;/p&gt;
&lt;p&gt;Samedi : Pernes-les-Fontaines, Petit Palais, Le Thor, Apt&lt;/p&gt;
&lt;p&gt;Dimanche : L&amp;rsquo;Isle sur la Sorgue Brocante, Carpentras Brocante, Coustellet&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Lavande&lt;/h3&gt;
&lt;img src=&quot;photos/provence-lavandes.jpg&quot; alt=&quot;Lavandes Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Vivre la lavande en Provence&lt;/p&gt;
&lt;p&gt;Distillerie, Visites guid&amp;eacute;es&lt;/p&gt;
&lt;p&gt;Mus&amp;eacute;e de la lavande Cabri&amp;egrave;res d&amp;rsquo;Avignon&lt;br /&gt; Mus&amp;eacute;e de la lavande Coustellet&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Rue des lavandes&lt;br /&gt; Six itin&amp;eacute;raires de la lavande pour tous les go&amp;ucirc;ts&lt;/p&gt;
&lt;p&gt;de Sault &amp;agrave; Valence (les plus grands champs)&lt;br /&gt; Vaison la Romaine&lt;br /&gt; Abbaye de S&amp;eacute;nanque (pr&amp;egrave;s de Gordes)&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Vin, Truffes, Fromage&lt;/h3&gt;
&lt;img src=&quot;photos/provence-vin.jpg&quot; alt=&quot;Vin Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Les vignobles de Provence comptent parmi les plus anciens de France. Les vins de la r&amp;eacute;gion du Luberon et du Ventoux sont tr&amp;egrave;s agr&amp;eacute;ables et de nombreux producteurs peuvent &amp;ecirc;tre visit&amp;eacute;s dans les environs. Mazan, Roussillon, Bonnieux, Apt, M&amp;eacute;nerbes (mus&amp;eacute;e du vin et de la truffe, mus&amp;eacute;e du tire-bouchon).&lt;/p&gt;
&lt;p&gt;Gigondas, Vaqueyras et la c&amp;eacute;l&amp;egrave;bre r&amp;eacute;gion de Ch&amp;acirc;teauneuf-des-Papes valent assur&amp;eacute;ment le d&amp;eacute;tour.&lt;/p&gt;
&lt;p&gt;^R&amp;eacute;gion viticole&lt;/p&gt;
&lt;p&gt;Pique-nique chez les vignerons&lt;/p&gt;
&lt;p&gt;L&amp;rsquo;hiver, la saison des truffes&lt;/p&gt;
&lt;p&gt;Les fromages de la France&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Olives&lt;/h3&gt;
&lt;img src=&quot;photos/provence-olive.jpg&quot; alt=&quot;Vin Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Les olives et l'huile d'olive font partie des stars de la Provence et sont incontournables dans la cuisine proven&amp;ccedil;ale.&lt;/p&gt;
&lt;p&gt;Moulin &amp;agrave; huile d&amp;rsquo;olive&lt;/p&gt;
&lt;p&gt;Castelas: Visite du moulin et d&amp;eacute;gustation&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Savon&lt;/h3&gt;
&lt;img src=&quot;photos/provence-savon.jpg&quot; alt=&quot;Vin Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Savon de Marseille&lt;/p&gt;
&lt;p&gt;Sur les traces de l'histoire du d&amp;eacute;veloppement de la fabrication du savon ; visite de l'usine, du mus&amp;eacute;e, visites guid&amp;eacute;es. D&amp;eacute;couverte d'un savoir-faire artisanal ancestral toujours vivant.&lt;/p&gt;
&lt;p&gt;Manufactures de savon, Visites guid&amp;eacute;es de l&amp;rsquo;usine&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;";

$champ_2="&lt;div class=&quot;offres&quot;&gt;
&lt;div&gt;
&lt;h3&gt;Provence at a glance&lt;/h3&gt;
&lt;a href=&quot;photos/Tourisme-carte.jpg&quot; data-lightbox=&quot;Provence&quot; data-title=&quot;La Provence &amp;agrave; la carte @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/Tourisme-carte.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Velleron is centrally located for the main sights of Provence:&lt;/p&gt;
&lt;p&gt;from Orange in the north to the Camargue in the south, from the famous lavender fields in the east to the Pont du Gard in the west.&lt;/p&gt;
&lt;p&gt;A selection of villages in Provence officially classified as &quot;Plus Beaux Villages de France&quot;:&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;Gordes&lt;/li&gt;
&lt;li&gt;Abbaye de S&amp;eacute;nanque&lt;/li&gt;
&lt;li&gt;Village des Bories&lt;/li&gt;
&lt;li&gt;M&amp;eacute;nerbes&lt;/li&gt;
&lt;li&gt;Roussillon&lt;/li&gt;
&lt;/ul&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Art, Culture &amp;amp; History&lt;/h3&gt;
&lt;img src=&quot;photos/provence-aix.jpg&quot; alt=&quot;Art, Culture &amp;amp; History&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Aix-en-Provence&amp;nbsp;; Paul C&amp;eacute;zanne, Sainte-Victoire, 1h30 Arles&amp;nbsp;; Amphitheatre, LUMA 1h15&lt;/p&gt;
&lt;p&gt;Avignon&amp;nbsp;; Pont Saint-Benezet, Festival, Palais des papes 30 min&lt;/p&gt;
&lt;p&gt;Baux &amp;amp; Carri&amp;egrave;res de Lumi&amp;egrave;re&amp;nbsp;; 50 min&lt;/p&gt;
&lt;p&gt;Bonnieux&amp;nbsp;; Pont Julien, 30 min&lt;/p&gt;
&lt;p&gt;Gordes&amp;nbsp;; Ch&amp;acirc;teau, Villages des Bories, Abbey S&amp;eacute;nanque 30 min&lt;/p&gt;
&lt;p&gt;Lacoste&amp;nbsp;; Ch&amp;acirc;teau and Village, 40 min&lt;/p&gt;
&lt;p&gt;Les Baux de Provence; Les Carri&amp;egrave;res de Lumi&amp;egrave;re, 1h&lt;/p&gt;
&lt;p&gt;Lourmarin&amp;nbsp;; Ch&amp;acirc;teau and Village, 50 min&lt;/p&gt;
&lt;p&gt;Orange; Antique theatre 40 min&lt;/p&gt;
&lt;p&gt;Pont du Gard, Arena of N&amp;icirc;mes 1h15&lt;/p&gt;
&lt;p&gt;Saint-Remy de Provence&amp;nbsp;; Vincent van Gogh, Roman city Glanum 35 min&lt;/p&gt;
&lt;p&gt;Uz&amp;egrave;s&amp;nbsp;; Village and Museum Georges Borias, 50 min&lt;/p&gt;
&lt;p&gt;Vaison-la-Romaine&amp;nbsp;; roman excavations, 50 min&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Provence by the sea&lt;/h3&gt;
&lt;img src=&quot;photos/provence-mer.jpg&quot; alt=&quot;&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Camargue, Regional Nature Park, Aigues-Mortes 1h30&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;C&amp;ocirc;te Bleue 1h&lt;/p&gt;
&lt;p&gt;Calanques and Cassis 1h30&lt;/p&gt;
&lt;p&gt;Saintes-Maries de la mer 1h30&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Marseille, Old harbour, la Bonne M&amp;egrave;re, 1h30&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Regions &amp;amp; Nature Parks, Mont Ventoux&lt;/h3&gt;
&lt;img src=&quot;photos/provence-ventoux.jpg&quot; alt=&quot;Mont Ventoux&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Alpilles - egional Nature Park;&lt;/p&gt;
&lt;p&gt;Saint-Remy-de Provence, Les Baux de Provence&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Avignon and Ch&amp;acirc;teauneuf-du-Pape&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;C&amp;ocirc;te du Rh&amp;ocirc;ne&amp;nbsp;;&lt;/p&gt;
&lt;p&gt;Roman heritage and wine-growing area, Orange&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Luberon;&lt;/p&gt;
&lt;p&gt;Bonnieux, Cavaillon, Cheval-Blanc, Gordes, Lacoste, Lauris, Les Taillades, Lourmarin, Maubec, M&amp;eacute;nerbes, M&amp;eacute;rindol, Opp&amp;egrave;de, Puget-sur-Durance, Puyvert, Robion, Roussillon (les Ocres de Roussillon)&lt;/p&gt;
&lt;p&gt;Rustrel;&lt;/p&gt;
&lt;p&gt;Colorado Proven&amp;ccedil;al&lt;/p&gt;
&lt;p&gt;Sorgue Valley ;&lt;/p&gt;
&lt;p&gt;L&amp;rsquo;Isle-sur-la-Sorgue (Little Venice)&lt;/p&gt;
&lt;p&gt;Ventoux&amp;nbsp;;&lt;br /&gt; Mont Ventoux, B&amp;eacute;doin, Mazan, Mormoiron, Les gorges de la Nesque&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Markets&lt;/h3&gt;
&lt;img src=&quot;photos/provence-marche.jpg&quot; alt=&quot;&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Monday : B&amp;eacute;doin, Cavaillon, St-Didier&lt;/p&gt;
&lt;p&gt;Tuesday : Gordes, Vaison la Romaine, t. Saturnin-les-Apt, Aix-en-Provence&lt;/p&gt;
&lt;p&gt;Wednesday : Saint Remy de Provence&lt;/p&gt;
&lt;p&gt;Thursday : Aix en Provence, L&amp;rsquo;Isle sur la Sorgue&lt;/p&gt;
&lt;p&gt;Friday : Carpentras, Lourmarin&lt;/p&gt;
&lt;p&gt;Saturday : Pernes-les-Fontaines, Petit Palais, Le Thor, Apt&lt;/p&gt;
&lt;p&gt;Sunday : L&amp;rsquo;Isle sur la Sorgue with Brocante, Carpentras Brocante, Coustellet&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Lavender&lt;/h3&gt;
&lt;img src=&quot;photos/provence-lavandes.jpg&quot; alt=&quot;Lavandes Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Experience lavender in Provence&lt;/p&gt;
&lt;p&gt;Distillery, Guided tours&lt;/p&gt;
&lt;p&gt;Lavender museum Cabri&amp;egrave;res d&amp;rsquo;Avignon&lt;br /&gt; Lavender museum Coustellet&lt;/p&gt;
&lt;p&gt;Lavender Street&lt;br /&gt; Six lavender routes for every taste&lt;/p&gt;
&lt;p&gt;Sault to Valence (biggest fields)&lt;br /&gt; Vaison la Romaine&lt;br /&gt; Abbaye de S&amp;eacute;nanque (near Gordes)&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Wine, Truffels, Cheese&lt;/h3&gt;
&lt;img src=&quot;photos/provence-vin.jpg&quot; alt=&quot;Vin Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;The wineries of Provence are among the oldest in France. The wines from the Luberon and Ventoux regions are very pleasant and many producers can be visited in the surrounding area. Mazan, Roussillon, Bonnieux, Apt, M&amp;eacute;nerbes (wine and truffle museum, corkscrew museum).&lt;/p&gt;
&lt;p&gt;Gigondas, Vaqueyras and the famous Ch&amp;acirc;teauneuf-des-Papes area are definitely worth a visit.&lt;/p&gt;
&lt;p&gt;Wine region Provence (france.fr)&lt;/p&gt;
&lt;p&gt;Picnic with the winegrowers&lt;/p&gt;
&lt;p&gt;Wintertime is truffle time&lt;/p&gt;
&lt;p&gt;France cheeses&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Olives&lt;/h3&gt;
&lt;img src=&quot;photos/provence-olive.jpg&quot; alt=&quot;Vin Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Olives and olive oil are among the stars of Provence and it is impossible to imagine Proven&amp;ccedil;al cuisine without them.&lt;/p&gt;
&lt;p&gt;Olive oil mill at Puym&amp;eacute;ras&lt;/p&gt;
&lt;p&gt;Castelas: Visit to the mill and tasting&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Soap&lt;/h3&gt;
&lt;img src=&quot;photos/provence-savon.jpg&quot; alt=&quot;Vin Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Savon de Marseille&lt;/p&gt;
&lt;p&gt;On the trail of the development history of soap making; factory visit, museum, guided tours. Discover a traditional craft that is still alive today.&lt;/p&gt;
&lt;p&gt;Soap manufacturers, Guided tours through the factory&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;";

$champ_3="&lt;div class=&quot;offres&quot;&gt;
&lt;div&gt;
&lt;h3&gt;Die Provence im &amp;Uuml;berblick&lt;/h3&gt;
&lt;a href=&quot;photos/Tourisme-carte.jpg&quot; data-lightbox=&quot;Provence&quot; data-title=&quot;La Provence &amp;agrave; la carte @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/Tourisme-carte.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p style=&quot;text-align: left;&quot;&gt;Velleron is centrally located for the main sights of Provence: from Orange in the north to the Camargue in the south, from the famous lavender fields in the east to the Pont du Gard in the west.&lt;/p&gt;
&lt;p&gt;A selection of villages in Provence officially classified as &quot;Plus Beaux Villages de France&quot;:&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;Gordes&lt;/li&gt;
&lt;li&gt;Abbaye de S&amp;eacute;nanque&lt;/li&gt;
&lt;li&gt;Village des Bories&lt;/li&gt;
&lt;li&gt;M&amp;eacute;nerbes&lt;/li&gt;
&lt;li&gt;Roussillon&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt;&lt;a href=&quot;https://i13.mnm.is/files/DucasseSchetter/attachment/78731297272/DUS_Magazin_Vaucluse_Var_2020_V5.pdf&quot; target=&quot;_blank&quot;&gt;Reiseideen Vaucluse und Var&lt;/a&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Kunst, Kultur &amp;amp; Geschichte&lt;/h3&gt;
&lt;img src=&quot;photos/provence-aix.jpg&quot; alt=&quot;&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Aix-en-Provence&amp;nbsp;; Paul C&amp;eacute;zanne, Sainte-Victoire, 1h30&lt;/p&gt;
&lt;p&gt;Arles&amp;nbsp;; Amphitheater, LUMA 1h15&lt;/p&gt;
&lt;p&gt;Avignon&amp;nbsp;; Pont Saint-Benezet, Festival, Papstpalast 30 min&lt;/p&gt;
&lt;p&gt;Baux &amp;amp; Les Carri&amp;egrave;res de Lumi&amp;egrave;re&amp;nbsp;; 50 min&lt;/p&gt;
&lt;p&gt;Bonnieux&amp;nbsp;; Pont Julien, 30 min&lt;/p&gt;
&lt;p&gt;Gordes&amp;nbsp;; Ch&amp;acirc;teau, Villages des Bories, Abbey de S&amp;eacute;nanque 30 min&lt;/p&gt;
&lt;p&gt;Lacoste&amp;nbsp;; Schloss und Dorf, 40 min&lt;/p&gt;
&lt;p&gt;Les Baux de Provence; Les Carri&amp;egrave;res de Lumi&amp;egrave;re, 1h&lt;/p&gt;
&lt;p&gt;Lourmarin&amp;nbsp;; Schloss und Dorf, 50 min&lt;/p&gt;
&lt;p&gt;Orange; Antikes Theater 40 min&lt;/p&gt;
&lt;p&gt;Pont du Gard, Arena von N&amp;icirc;mes 1h15&lt;/p&gt;
&lt;p&gt;Saint-Remy de Provence&amp;nbsp;; Vincent van Gogh, r&amp;ouml;m. Stad Glanum 35 min&lt;/p&gt;
&lt;p&gt;Uz&amp;egrave;s&amp;nbsp;; Dorf und Mus&amp;eacute;e Georges Borias, 50 min&lt;/p&gt;
&lt;p&gt;Vaison-la-Romaine&amp;nbsp;; R&amp;ouml;mische Ausgrabungen, 50 min&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Die Provence am Meer&lt;/h3&gt;
&lt;img src=&quot;photos/provence-mer.jpg&quot; alt=&quot;&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Camargue, Regionaler Naturpark, Aigues-Mortes 1h30&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;C&amp;ocirc;te Bleue 1h&lt;/p&gt;
&lt;p&gt;Calanques und Cassis 1h30&lt;/p&gt;
&lt;p&gt;Saintes-Maries de la mer 1h30&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Marseille, Alter Hafen, la Bonne M&amp;egrave;re, 1h30&lt;/p&gt;
&lt;p&gt;Saint-Remy de Provence&amp;nbsp;; Vincent van Gogh, r&amp;ouml;m. Stadt Glanum 35 min&lt;/p&gt;
&lt;p&gt;Uz&amp;egrave;s&amp;nbsp;; Dorf &amp;amp; Mus&amp;eacute;e Georges Borias, 50 min&lt;/p&gt;
&lt;p&gt;Vaison-la-Romaine&amp;nbsp;; R&amp;ouml;mische Ausgrabungen, 50 min&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Regionen &amp;amp; Naturparks, Mont Ventoux&lt;/h3&gt;
&lt;img src=&quot;photos/provence-ventoux.jpg&quot; alt=&quot;Mont Ventoux&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Alpilles - Regionaler Naturpark&amp;nbsp;;&lt;/p&gt;
&lt;p&gt;Saint-Remy-de Provence, Les Baux de Provence&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Avignon und Ch&amp;acirc;teauneuf-du-Pape&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;C&amp;ocirc;te du Rh&amp;ocirc;ne&amp;nbsp;;&lt;/p&gt;
&lt;p&gt;R&amp;ouml;misches Kulturerbe und Weinanbaugebiet, Orange&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Luberon;&lt;/p&gt;
&lt;p&gt;Bonnieux, Cavaillon, Cheval-Blanc, Gordes, Lacoste, Lauris, Les Taillades, Lourmarin, Maubec, M&amp;eacute;nerbes, M&amp;eacute;rindol, Opp&amp;egrave;de, Puget-sur-Durance, Puyvert, Robion, Roussillon (les Ocres de Roussillon)&lt;/p&gt;
&lt;p&gt;Rustrel;&lt;/p&gt;
&lt;p&gt;Colorado Proven&amp;ccedil;al&lt;/p&gt;
&lt;p&gt;Sorgue-Tal&amp;nbsp;;&lt;/p&gt;
&lt;p&gt;L&amp;rsquo;Isle-sur-la-Sorgue (Kleinvenedig),&lt;/p&gt;
&lt;p&gt;Ventoux&amp;nbsp;;&lt;br /&gt; Mont Ventoux, B&amp;eacute;doin, Mazan, Mormoiron, Les gorges de la Nesque&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;M&amp;auml;rkte&lt;/h3&gt;
&lt;img src=&quot;photos/provence-marche.jpg&quot; alt=&quot;&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Montag : B&amp;eacute;doin, Cavaillon, St-Didier&lt;/p&gt;
&lt;p&gt;Dienstag : Gordes, Vaison la Romaine, t. Saturnin-les-Apt, Aix-en-Provence&lt;/p&gt;
&lt;p&gt;Mittwoch : Saint Remy de Provence&lt;/p&gt;
&lt;p&gt;Donnerstag : Aix en Provence, L&amp;rsquo;Isle sur la Sorgue&lt;/p&gt;
&lt;p&gt;Freitag : Carpentras, Lourmarin&lt;/p&gt;
&lt;p&gt;Samstag : Pernes-les-Fontaines, Petit Palais, Le Thor, Apt&lt;/p&gt;
&lt;p&gt;Sonntag : L&amp;rsquo;Isle sur la Sorgue mit Brocante, Carpentras Brocante, Coustellet&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Lavendel&lt;/h3&gt;
&lt;img src=&quot;photos/provence-lavandes.jpg&quot; alt=&quot;Lavandes Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Lavendel in der Provence erleben&lt;/p&gt;
&lt;p&gt;Distillerie, Gef&amp;uuml;hrte Touren&lt;/p&gt;
&lt;p&gt;Lavendelmuseum Cabri&amp;egrave;res d&amp;rsquo;Avignon&lt;br /&gt; Lavendelmuseum Coustellet&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Lavendelstra&amp;szlig;e&lt;br /&gt; Sechs Lavendelrouten f&amp;uuml;r jeden Geschmack&lt;/p&gt;
&lt;p&gt;Sault bis Valence (gr&amp;ouml;sste Felder)&lt;br /&gt; Vaison la Romaine&lt;br /&gt; Zisterzienserabtei von S&amp;eacute;nanque (bei Gordes)&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Wein, Tr&amp;uuml;ffel, K&amp;auml;se&lt;/h3&gt;
&lt;img src=&quot;photos/provence-vin.jpg&quot; alt=&quot;Vin Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Die Weing&amp;uuml;ter der Provence z&amp;auml;hlen zu den &amp;auml;ltesten Frankreichs. Die Weine aus der Region des Luberon und des Ventoux sind sehr angenehm und in der Umgebung k&amp;ouml;nnen viele Produzenten besucht werden. Mazan, Roussillon, Bonnieux, Apt, M&amp;eacute;nerbes (Wein- und Tr&amp;uuml;ffelmuseum, Korkenziehermuseum)&lt;/p&gt;
&lt;p&gt;Gigondas, Vaqueyras und das ber&amp;uuml;hmte Ch&amp;acirc;teauneuf-des-Papes Gebiet sind auf jeden Fall einen Besuch wert.&lt;br /&gt; Weinregion Provence (france.fr)&lt;/p&gt;
&lt;p&gt;Picknick bei den Winzern&lt;/p&gt;
&lt;p&gt;Winterzeit ist Tr&amp;uuml;ffelzeit&lt;/p&gt;
&lt;p&gt;Frankreichs K&amp;auml;sesorten&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Oliven&lt;/h3&gt;
&lt;img src=&quot;photos/provence-olive.jpg&quot; alt=&quot;Vin Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Oliven und Oliven&amp;ouml;l geh&amp;ouml;ren zu den Stars der Provence und sind aus der provenzalischen K&amp;uuml;che nicht wegzudenken.&lt;/p&gt;
&lt;p&gt;Oliven&amp;ouml;lm&amp;uuml;hle in Puym&amp;eacute;ras&lt;/p&gt;
&lt;p&gt;Castelas: Besuch der M&amp;uuml;hle und Verkostung&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Seife&lt;/h3&gt;
&lt;img src=&quot;photos/provence-savon.jpg&quot; alt=&quot;Vin Provence&quot; /&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Auf den Spuren der Entwicklungsgeschichte der Seifenherstellung; Fabrikbesuch, Museum, F&amp;uuml;hrungen. Entdecken Sie ein alt&amp;uuml;berliefertes, nach wie vor lebendiges handwerkliches K&amp;ouml;nnen.&lt;/p&gt;
&lt;p&gt;Seifenmanufakturen, F&amp;uuml;hrungen durch die Fabrik&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;";

$champ_4="";

$champ_5="";

$champ_6="";

$champ_7="";

$champ_8="";

$champ_9="";

$champ_10="";

$champ_11="";

$champ_12="";

$champ_13="";

$champ_14="";

$champ_15="";

$champ_16="";

$champ_17="";

$champ_18="";

$champ_19="";

$champ_20="";

?>
