<?
/* Ce fichier contient les parametres de la page a afficher */

/*************************/
/* champs pour affichage */
/*************************/

$champ_1="&lt;div class=&quot;offres&quot;&gt;
&lt;div&gt;
&lt;h3&gt;Velleron - &amp;nbsp;le village&lt;/h3&gt;
&lt;a href=&quot;photos/velleron01.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Velleron @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron01.jpg&quot; alt=&quot;Velleron&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Velleron est situ&amp;eacute; entre Pernes-les-Fontaines et L'Isle-sur-la-Sorgue, au centre de la plaine agricole du &lt;a href=&quot;https://de.wikipedia.org/wiki/Comtat_Venaissin&quot;&gt;Comtat&lt;/a&gt;.&lt;/p&gt;
&lt;p&gt;Ce village typiquement proven&amp;ccedil;al, situ&amp;eacute; &amp;agrave; seulement 20 km d'Avignon, est le point de d&amp;eacute;part id&amp;eacute;al pour des excursions en Provence.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;March&amp;eacute; Agricole&lt;/h3&gt;
&lt;a href=&quot;photos/velleron02.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Bauernmarkt @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron02.jpg&quot; alt=&quot;Bauernmarkt&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;En quelques ann&amp;eacute;es, le c&amp;eacute;l&amp;egrave;bre march&amp;eacute; agricole de Velleron est devenu une v&amp;eacute;ritable institution dans le Vaucluse et bien au-del&amp;agrave;.&lt;/p&gt;
&lt;p&gt;Ouvert toute l'ann&amp;eacute;e, le march&amp;eacute; surprend par la vari&amp;eacute;t&amp;eacute; des produits r&amp;eacute;gionaux et saisonniers qu'il propose.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Collines et Canal&lt;/h3&gt;
&lt;a href=&quot;photos/velleron03.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;H&amp;uuml;gel und Kanal @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron03.jpg&quot; alt=&quot;Bauernmarkt&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Le Canal de Carpentras a &amp;eacute;t&amp;eacute; construit de 1849 &amp;agrave; 1857 comme ouvrage d'irrigation. La prise d'eau se fait &amp;agrave; Mallemort dans la Durance. La longueur du canal principal est de 69 kilom&amp;egrave;tres. L'aqueduc de Galas pr&amp;egrave;s de Fontaine-de-Vaucluse est l'un des ouvrages le long du canal.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Les collines pr&amp;egrave;s de Velleron sont les premiers contreforts des montagnes du Vaucluse. Elles se pr&amp;ecirc;tent parfaitement aux promenades, aux petites randonn&amp;eacute;es, &amp;agrave; la course &amp;agrave; pied, au v&amp;eacute;lo et au VTT.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Grottes de Thouzon&lt;/h3&gt;
&lt;a href=&quot;photos/velleron04.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Die Grotten von Thouzon @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron04.jpg&quot; alt=&quot;Die Grotten von Thouzon&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Les grottes de Thouzon ont &amp;eacute;t&amp;eacute; d&amp;eacute;couvertes en 1902 lors de l'exploitation d'une carri&amp;egrave;re. Elles sont les seules grottes naturelles de Provence &amp;agrave; &amp;ecirc;tre ouvertes au tourisme.&lt;/p&gt;
&lt;p&gt;Les stalactites jaunes et dor&amp;eacute;es constituent le c&amp;oelig;ur des grottes. Pendant la visite, on traverse le lit fossile d'une ancienne rivi&amp;egrave;re souterraine.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Ferme aux papillons&lt;/h3&gt;
&lt;a href=&quot;photos/velleron05.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Schmetterlingsfarm @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron05.jpg&quot; alt=&quot;Schmetterlingsfarm&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;&lt;a href=&quot;https://www.lecarbetamazonien.fr/&quot;&gt;Le Carbet Amazonien&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;La serre d'&amp;eacute;levage de 500m2 est un petit paradis. Les plantes tropicales reproduisent la for&amp;ecirc;t tropicale et permettent la m&amp;eacute;tamorphose des papillons, qui peuvent se d&amp;eacute;velopper, se nourrir et se reproduire naturellement.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Pernes les Fontaines&lt;/h3&gt;
&lt;a href=&quot;photos/velleron06.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Pernes les Fontaines @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron06.jpg&quot; alt=&quot;Pernes les Fontaines&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Pernes-les-Fontaines est aussi appel&amp;eacute;e la &quot;perle du Comtat&quot;. Ancienne capitale du Comtat Venaissin avant de tomber sous la domination des papes, elle a conserv&amp;eacute; de cette &amp;eacute;poque un patrimoine historique exceptionnel. D'abord Paternus, puis Paternae, puis Pernes, la ville, dot&amp;eacute;e d'une source naturelle et qui comptait 36 fontaines en 1936, est finalement devenue &quot;Pernes-les-Fontaines&quot;.&lt;/p&gt;
&lt;p&gt;Et des fontaines, il y en a ! Pas moins de 40 - le double si l'on compte les fontaines priv&amp;eacute;es - datant du 18e si&amp;egrave;cle, dont plusieurs sont class&amp;eacute;es monuments historiques.&lt;/p&gt;
&lt;br /&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;L&amp;rsquo;Isle sur la Sorgue&lt;/h3&gt;
&lt;a href=&quot;photos/velleron07.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;L&amp;rsquo;Isle sur la Sorgue @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron07.jpg&quot; alt=&quot;L&amp;rsquo;Isle sur la Sorgue&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;'Isle-sur-la-Sorgue tire son nom de la Sorgue, qui prend sa source quelques kilom&amp;egrave;tres en amont &amp;agrave; Fontaine-de-Vaucluse. Celle-ci se divise en de nombreux bras et canaux qui divisent la ville en plusieurs &amp;icirc;les. C'est pour cette raison que la ville est parfois surnomm&amp;eacute;e la Venise comtadine.&lt;/p&gt;
&lt;p&gt;Depuis pr&amp;egrave;s de 40 ans, la brocante a forg&amp;eacute; l'identit&amp;eacute; de la ville de L'Isle et lui a conf&amp;eacute;r&amp;eacute; une notori&amp;eacute;t&amp;eacute; internationale. L'Isle-sur-la-Sorgue est la troisi&amp;egrave;me plus grande plateforme d'antiquit&amp;eacute;s en Europe, apr&amp;egrave;s Saint-Ouen et Londres.&lt;/p&gt;
&lt;p&gt;Le march&amp;eacute; flottant a lieu une fois par an : Il se tient le premier dimanche d'ao&amp;ucirc;t sur la Sorgue.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Fontaine de Vaucluse&lt;/h3&gt;
&lt;a href=&quot;photos/velleron08.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Fontaine de Vaucluse @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron08.jpg&quot; alt=&quot;Fontaine de Vaucluse&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;&lt;a href=&quot;https://www.fontainedevaucluse.fr/&quot;&gt;Fontaine de Vaucluse&lt;/a&gt; est un village embl&amp;eacute;matique du Luberon. C'est ici que jaillit la c&amp;eacute;l&amp;egrave;bre source de la Sorgue. Avec un d&amp;eacute;bit annuel de 630 millions de m&amp;egrave;tres cubes, elle est la source la plus puissante de France. Ses eaux vert &amp;eacute;meraude, g&amp;eacute;n&amp;eacute;ralement calmes en &amp;eacute;t&amp;eacute;, deviennent spectaculaires en p&amp;eacute;riode de crue (en automne et au printemps) : 90 m&amp;sup3; par seconde se d&amp;eacute;versent dans le lit de la Sorgue. En toutes saisons, des sources secondaires alimentent la rivi&amp;egrave;re et forment un tr&amp;egrave;s beau plan d'eau ombrag&amp;eacute; par d'immenses platanes.&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://www.fontainedevaucluse.fr/&quot;&gt;Fontaine de Vaucluse&lt;/a&gt; ist ein symboltr&amp;auml;chtiges Dorf im Luberon. Hier entspringt die ber&amp;uuml;hmte Quelle der Sorgue. Sie ist mit einer j&amp;auml;hrlichen Wassermenge von 630 Millionen Kubikmetern die st&amp;auml;rkste Quelle in Frankreich. Das smaragdgr&amp;uuml;ne Wasser, das im Sommer meist ruhig ist, wird bei Hochwasser (im Herbst und Fr&amp;uuml;hjahr) spektakul&amp;auml;r: 90 m&amp;sup3; pro Sekunde ergie&amp;szlig;en sich in das Flussbett der Sorgue. Zu allen Jahreszeiten speisen sekund&amp;auml;re Quellen den Fluss und bilden eine sehr sch&amp;ouml;ne Wasserfl&amp;auml;che, die von riesigen Platanen beschattet wird.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;In der Umgebung&lt;/h3&gt;
&lt;a href=&quot;photos/velleron09.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;In der Umgebung @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron09.jpg&quot; alt=&quot;In der Umgebung&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Le Thor&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://de.wikipedia.org/wiki/Le_Thor#/media/Datei:Le_Thor_(Vaucluse,_Fr)_City_gate.JPG&quot;&gt;Porte de la ville avec magnifique clocher et horloger&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Ch&amp;acirc;teauneuf-de-Gadagne&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://islesurlasorguetourisme.com/bouger/nature-sport/autres-activites/323002-parc-de-larbousiere&quot;&gt;Plateau et Parc de L'Arbousi&amp;egrave;re&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://www.provenceweb.fr/f/vaucluse/saturnin-avignon/saturnin-avignon.htm?r=1&amp;amp;Largeur=1536&amp;amp;Hauteur=864&quot;&gt;Saint-Saturnin-l&amp;egrave;s-Avignon&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Chapelle Notre Dame du Sacr&amp;eacute; Coeur (1947)&lt;/p&gt;
&lt;p&gt;Place des Caf&amp;eacute;s&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://www.les-plus-beaux-villages-de-france.org/fr/nos-villages/venasque/&quot;&gt;Venasque&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Ville m&amp;eacute;di&amp;eacute;vale avec trois tours sarrasines. Ruelles escarp&amp;eacute;es et maisons en pierre dor&amp;eacute;e, &amp;eacute;glise et cath&amp;eacute;drale Notre-Dame et un magnifique baptist&amp;egrave;re du 11e si&amp;egrave;cle.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Carpentras&lt;/p&gt;
&lt;p&gt;Brocante le dimanche matin et march&amp;eacute; hebdomadaire le vendredi matin dans le centre-ville&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Cavaillon&lt;/p&gt;
&lt;p&gt;Plus ancienne synagogue de France (14e si&amp;egrave;cle)&lt;/p&gt;
&lt;p&gt;Cath&amp;eacute;drale de Cavaillon&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://www.avignon-et-provence.com/en/traditions/melon-festival-cavaillon&quot;&gt;Festival&lt;/a&gt; du melon&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;";

$champ_2="&lt;div class=&quot;offres&quot;&gt;
&lt;div&gt;
&lt;h3&gt;Velleron &amp;ndash; The village&lt;/h3&gt;
&lt;a href=&quot;photos/velleron01.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Velleron @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron01.jpg&quot; alt=&quot;Velleron&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Velleron is located between Pernes-les-Fontaines and L'Isle-sur-la-Sorgue in the centre of the agricultural plain of the Comtat.&lt;/p&gt;
&lt;p&gt;The typical Proven&amp;ccedil;al village is only 20 km from Avignon and an ideal starting point for excursions in Provence.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Farmers&amp;rsquo; market&lt;/h3&gt;
&lt;a href=&quot;photos/velleron02.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Bauernmarkt @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron02.jpg&quot; alt=&quot;Bauernmarkt&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Within a few years, the famous farmers' market in Velleron has become a real institution in the Vaucluse and far beyond.&lt;/p&gt;
&lt;p&gt;The market is open all year round and surprises with a variety of regional and seasonal products.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Collines and canal&lt;/h3&gt;
&lt;a href=&quot;photos/velleron03.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;H&amp;uuml;gel und Kanal @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron03.jpg&quot; alt=&quot;Bauernmarkt&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;The &lt;a href=&quot;https://www.canaldecarpentras.com/&quot;&gt;Canal de Carpentras&lt;/a&gt; was built from 1849-1857 as an irrigation structure. The water is taken from the Durance at Mallemort. The length of the main canal is 69 kilometres. The aqueduct of Galas near Fontaine-de-Vaucluse is one of the structures along the canal.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;The Collines near Velleron are the first foothills of the Vaucluse mountains. They are excellent for walks, short hikes, running, cycling and mountain biking.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;The Caves of Thouzon&lt;/h3&gt;
&lt;a href=&quot;photos/velleron04.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Die Grotten von Thouzon @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron04.jpg&quot; alt=&quot;Die Grotten von Thouzon&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;The Thouzon caves were discovered in 1902 during the exploitation of a quarry. They are the only natural caves in Provence open to tourism.&lt;/p&gt;
&lt;p&gt;The yellow-gold stalactites are the centrepiece of the caves. During the visit, you will walk over the fossilised bed of an ancient underground river.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Butterfly farm&lt;/h3&gt;
&lt;a href=&quot;photos/velleron05.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Schmetterlingsfarm @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron05.jpg&quot; alt=&quot;Schmetterlingsfarm&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;&lt;a href=&quot;https://www.lecarbetamazonien.fr/&quot;&gt;Le Carbet Amazonien&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;The 500m2 breeding greenhouse is a little paradise. The tropical plants recreate the rainforest and allow the butterflies to metamorphose, develop, feed and reproduce naturally.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Pernes les Fontaines&lt;/h3&gt;
&lt;a href=&quot;photos/velleron06.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Pernes les Fontaines @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron06.jpg&quot; alt=&quot;Pernes les Fontaines&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Pernes-les-Fontaines is also called the &quot;Pearl of the Comtat&quot;. Former capital of the Comtat Venaissin before falling under the rule of the popes, it has preserved an exceptional historical heritage from that period. First Paternus, then Paternae, then Pernes, the town endowed with a natural spring and having 36 fountains in 1936, finally became &quot;Pernes-les-Fontaines&quot;.&lt;/p&gt;
&lt;p&gt;And fountains there are! No fewer than 40 - twice as many if you count the private fountains - dating back to the 18th century, several of which are listed.&lt;/p&gt;
&lt;br /&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;L&amp;rsquo;Isle sur la Sorgue&lt;/h3&gt;
&lt;a href=&quot;photos/velleron07.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;L&amp;rsquo;Isle sur la Sorgue @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron07.jpg&quot; alt=&quot;L&amp;rsquo;Isle sur la Sorgue&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;L'Isle-sur-la-Sorgue takes its name from the Sorgue, which rises a few kilometres upstream in Fontaine-de-Vaucluse. This divides into numerous arms and canals that divide the town into several islands. For this reason, the town is sometimes called the Venice of the Comtadine.&lt;/p&gt;
&lt;p&gt;For almost 40 years, the flea market has shaped the identity of the town of L'Isle and given it an international reputation. L'Isle-sur-la-Sorgue is the third largest platform for the antiques trade in Europe, after Saint-Ouen and London.&lt;/p&gt;
&lt;p&gt;The floating market takes place once a year: It is held on the first Sunday in August on the Sorgue.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Fontaine de Vaucluse&lt;/h3&gt;
&lt;a href=&quot;photos/velleron08.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Fontaine de Vaucluse @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron08.jpg&quot; alt=&quot;Fontaine de Vaucluse&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;&lt;a href=&quot;https://www.fontainedevaucluse.fr/&quot;&gt;Fontaine de Vaucluse&lt;/a&gt; is an emblematic village in the Luberon. The famous spring of the Sorgue rises here. With an annual water volume of 630 million cubic metres, it is the most powerful spring in France. The emerald-green water, which is usually calm in summer, becomes spectacular at high water (in autumn and spring): 90 m&amp;sup3; per second pour into the Sorgue riverbed. In all seasons, secondary springs feed the river and form a very beautiful water surface shaded by huge plane trees.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;In the surrounding area&lt;/h3&gt;
&lt;a href=&quot;photos/velleron09.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;In der Umgebung @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron09.jpg&quot; alt=&quot;In der Umgebung&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Le Thor&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://de.wikipedia.org/wiki/Le_Thor#/media/Datei:Le_Thor_(Vaucluse,_Fr)_City_gate.JPG&quot;&gt;City gate with magnificent bell tower and clock&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Ch&amp;acirc;teauneuf-de-Gadagne&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://islesurlasorguetourisme.com/bouger/nature-sport/autres-activites/323002-parc-de-larbousiere&quot;&gt;Plateau and Parc de L'Arbousi&amp;egrave;re&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://www.provenceweb.fr/f/vaucluse/saturnin-avignon/saturnin-avignon.htm?r=1&amp;amp;Largeur=1536&amp;amp;Hauteur=864&quot;&gt;Saint-Saturnin-l&amp;egrave;s-Avignon&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Chapel of Notre Dame du Sacr&amp;eacute; Coeur (1947)&lt;/p&gt;
&lt;p&gt;Place des Caf&amp;eacute;s&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://www.les-plus-beaux-villages-de-france.org/fr/nos-villages/venasque/&quot;&gt;Venasque&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Medieval town with three Saracen towers. Steep streets and houses of golden stone, Notre-Dame church and cathedral and a beautiful 11th century baptistery.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Carpentras&lt;/p&gt;
&lt;p&gt;Brocante on Sunday morning and weekly market on Friday morning in the city centre&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Cavaillon&lt;/p&gt;
&lt;p&gt;Oldest synagogue in France (14th c.)&lt;/p&gt;
&lt;p&gt;Cavaillon Cathedral&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://www.avignon-et-provence.com/en/traditions/melon-festival-cavaillon&quot;&gt;&lt;span lang=&quot;it-IT&quot;&gt;Melon Festival&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;span lang=&quot;it-IT&quot;&gt;&lt;a href=&quot;https://www.luberoncoeurdeprovence.com/bouger/la-via-ferrata-de-cavaillon&quot;&gt;Via Ferrata&lt;/a&gt; &lt;/span&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;";

$champ_3="&lt;div class=&quot;offres&quot;&gt;
&lt;div&gt;
&lt;h3&gt;Velleron - das Dorf&lt;/h3&gt;
&lt;a href=&quot;photos/velleron01.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Velleron @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron01.jpg&quot; alt=&quot;Velleron&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Velleron liegt zwischen Pernes-les-Fontaines und L'Isle-sur-la-Sorgue im Zentrum der landwirtschaftlich genutzten Ebene des &lt;a href=&quot;https://de.wikipedia.org/wiki/Comtat_Venaissin&quot;&gt;Comtat&lt;/a&gt;.&lt;/p&gt;
&lt;p&gt;Das typisch provenzalische Dorf ist nur 20 km von Avignon entfernt und idealer Ausgangspunkt f&amp;uuml;r Ausfl&amp;uuml;ge in der Provence.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Bauernmarkt&lt;/h3&gt;
&lt;a href=&quot;photos/velleron02.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Bauernmarkt @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron02.jpg&quot; alt=&quot;Bauernmarkt&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Innerhalb weniger Jahre ist der ber&amp;uuml;hmte Bauernmarkt in Velleron zu einer echten Institution in der Vaucluse und weit dar&amp;uuml;ber hinaus geworden.&lt;/p&gt;
&lt;p&gt;Der Markt ist ganzj&amp;auml;hrig ge&amp;ouml;ffnet und &amp;uuml;berrascht mit einer Vielzahl an regionalen und saisonalen Produkten.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;H&amp;uuml;gel und Kanal&lt;/h3&gt;
&lt;a href=&quot;photos/velleron03.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;H&amp;uuml;gel und Kanal @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron03.jpg&quot; alt=&quot;Bauernmarkt&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Der &lt;a href=&quot;https://www.canaldecarpentras.com/&quot;&gt;Canal de Carpentras&lt;/a&gt; wurde von 1849-1857 als Bew&amp;auml;sserungsbauwerk errichtet. Die Wasseraufnahme erfolgt bei &lt;a href=&quot;https://de.wikipedia.org/wiki/Mallemort&quot;&gt;Mallemort&lt;/a&gt; aus der &lt;a href=&quot;https://de.wikipedia.org/wiki/Durance&quot;&gt;Durance&lt;/a&gt;. Die L&amp;auml;nge des Hauptkanals betr&amp;auml;gt 69 Kilometer. Der &lt;a href=&quot;https://www.tripadvisor.de/Attraction_Review-g608806-d20928038-Reviews-Pont_aqueduc_De_Galas-Fontaine_de_Vaucluse_Vaucluse_Provence_Alpes_Cote_d_Azur.html&quot;&gt;Aqu&amp;auml;dukt von Galas&lt;/a&gt; bei Fontaine-de-Vaucluse ist eines der Bauwerke entlang des Kanals.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Die Collines bei Velleron sind die ersten Ausl&amp;auml;ufer der Berge des Vaucluse. Sie eignen sich ausgezeichnet f&amp;uuml;r Spazierg&amp;auml;nge, kleine Wanderungen, zum Laufen, Radfahren und Mountainbiken.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Die Grotten von Thouzon&lt;/h3&gt;
&lt;a href=&quot;photos/velleron04.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Die Grotten von Thouzon @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron04.jpg&quot; alt=&quot;Die Grotten von Thouzon&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Die &lt;a href=&quot;https://www.grottes-thouzon.com/&quot;&gt;Grotten von Thouzon&lt;/a&gt; wurden 1902 bei der Ausbeutung eines Steinbruchs entdeckt. Sie sind die einzigen nat&amp;uuml;rliche Grotten in der Provence, die f&amp;uuml;r den Tourismus zug&amp;auml;nglich sind.&lt;/p&gt;
&lt;p&gt;Das Herzst&amp;uuml;ck der H&amp;ouml;hlen bilden die gelb-goldenen Stalaktiten. W&amp;auml;hrend der Besichtigung geht es &amp;uuml;ber das fossile Bett eines alten unterirdischen Flusses.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Schmetterlingsfarm&lt;/h3&gt;
&lt;a href=&quot;photos/velleron05.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Schmetterlingsfarm @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron05.jpg&quot; alt=&quot;Schmetterlingsfarm&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;&lt;a href=&quot;https://www.lecarbetamazonien.fr/&quot;&gt;Le Carbet Amazonien&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Das 500m2 grosse Zuchtgew&amp;auml;chshaus ist ein kleines Paradies. Die tropischen Pflanzen bilden den Regenwald nach und erm&amp;ouml;glichen die Metamorphose der Schmetterlinge, die sich ganz nat&amp;uuml;rlich entwickeln, ern&amp;auml;hren und vermehren k&amp;ouml;nnen.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Pernes les Fontaines&lt;/h3&gt;
&lt;a href=&quot;photos/velleron06.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Pernes les Fontaines @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron06.jpg&quot; alt=&quot;Pernes les Fontaines&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Pernes-les-Fontaines wird auch die &quot;Perle des Comtat&quot; genannt. Als ehemalige Hauptstadt des Comtat Venaissin, bevor sie unter die Herrschaft der P&amp;auml;pste fiel, hat sie aus dieser Zeit ein au&amp;szlig;ergew&amp;ouml;hnliches historisches Erbe bewahrt. Zuerst Paternus, dann Paternae, dann Pernes, die Stadt, die mit einer nat&amp;uuml;rlichen Quelle ausgestattet ist und 1936 36 Brunnen hatte, wurde schlie&amp;szlig;lich zu &quot;Pernes-les-Fontaines&quot;.&lt;/p&gt;
&lt;p&gt;Und Brunnen gibt es! Nicht weniger als 40 - doppelt so viele, wenn man die privaten Brunnen mitz&amp;auml;hlt - aus dem 18. Jahrhundert, von denen mehrere unter Denkmalschutz stehen.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;L&amp;rsquo;Isle sur la Sorgue&lt;/h3&gt;
&lt;a href=&quot;photos/velleron07.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;L&amp;rsquo;Isle sur la Sorgue @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron07.jpg&quot; alt=&quot;L&amp;rsquo;Isle sur la Sorgue&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;L'Isle-sur-la-Sorgue hat seinen Namen von der Sorgue, die einige Kilometer flussaufw&amp;auml;rts in Fontaine-de-Vaucluse entspringt. Diese teilt sich in zahlreiche Arme und Kan&amp;auml;le, die die Stadt in mehrere Inseln unterteilen. Aus diesem Grund wird die Stadt manchmal auch als Venedig der Comtadine bezeichnet.&lt;/p&gt;
&lt;p&gt;Seit fast 40 Jahren hat der Tr&amp;ouml;delmarkt die Identit&amp;auml;t der Stadt L'Isle gepr&amp;auml;gt und ihr einen internationalen Bekanntheitsgrad verschafft. L'Isle-sur-la-Sorgue ist nach Saint-Ouen und London die drittgr&amp;ouml;&amp;szlig;te Plattform f&amp;uuml;r den Antiquit&amp;auml;tenhandel in Europa.&lt;/p&gt;
&lt;p&gt;Einmal im Jahr findet der schwimmende Markt statt: Er wird am ersten Sonntag im August auf der Sorgue abgehalten.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;Fontaine de Vaucluse&lt;/h3&gt;
&lt;a href=&quot;photos/velleron08.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;Fontaine de Vaucluse @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron08.jpg&quot; alt=&quot;Fontaine de Vaucluse&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;&lt;a href=&quot;https://www.fontainedevaucluse.fr/&quot;&gt;Fontaine de Vaucluse&lt;/a&gt; ist ein symboltr&amp;auml;chtiges Dorf im Luberon. Hier entspringt die ber&amp;uuml;hmte Quelle der Sorgue. Sie ist mit einer j&amp;auml;hrlichen Wassermenge von 630 Millionen Kubikmetern die st&amp;auml;rkste Quelle in Frankreich. Das smaragdgr&amp;uuml;ne Wasser, das im Sommer meist ruhig ist, wird bei Hochwasser (im Herbst und Fr&amp;uuml;hjahr) spektakul&amp;auml;r: 90 m&amp;sup3; pro Sekunde ergie&amp;szlig;en sich in das Flussbett der Sorgue. Zu allen Jahreszeiten speisen sekund&amp;auml;re Quellen den Fluss und bilden eine sehr sch&amp;ouml;ne Wasserfl&amp;auml;che, die von riesigen Platanen beschattet wird.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div&gt;
&lt;h3&gt;In der Umgebung&lt;/h3&gt;
&lt;a href=&quot;photos/velleron09.jpg&quot; data-lightbox=&quot;Velleron&quot; data-title=&quot;In der Umgebung @ Villa Velleron&quot;&gt;&lt;img src=&quot;photos/velleron09.jpg&quot; alt=&quot;In der Umgebung&quot; /&gt;&lt;/a&gt;
&lt;div class=&quot;descriptionOffre&quot;&gt;
&lt;p&gt;Le Thor&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://de.wikipedia.org/wiki/Le_Thor#/media/Datei:Le_Thor_(Vaucluse,_Fr)_City_gate.JPG&quot;&gt;Stadttor mit prachtvollem Glockenturm und Uhr&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Ch&amp;acirc;teauneuf-de-Gadagne&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://islesurlasorguetourisme.com/bouger/nature-sport/autres-activites/323002-parc-de-larbousiere&quot;&gt;Plateau und Parc de L'Arbousi&amp;egrave;re&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://www.provenceweb.fr/f/vaucluse/saturnin-avignon/saturnin-avignon.htm?r=1&amp;amp;Largeur=1536&amp;amp;Hauteur=864&quot;&gt;Saint-Saturnin-l&amp;egrave;s-Avignon&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Kapelle Notre Dame du Sacr&amp;eacute; Coeur (1947)&lt;/p&gt;
&lt;p&gt;Place des Caf&amp;eacute;s&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://www.les-plus-beaux-villages-de-france.org/fr/nos-villages/venasque/&quot;&gt;Venasque&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;Mittelalterliche Stadt mit drei Sarazenent&amp;uuml;rmen. Steile Gassen und H&amp;auml;user aus goldenem Stein, Kirche und Kathedrale Notre-Dame und ein wundersch&amp;ouml;nes Baptisterium aus dem 11. Jahrhundert.&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Carpentras&lt;/p&gt;
&lt;p&gt;Brocante am Sonntagmorgen und Wochenmarkt am Freitagmorgen in der Innenstadt&lt;/p&gt;
&lt;p&gt;&amp;nbsp;&lt;/p&gt;
&lt;p&gt;Cavaillon&lt;/p&gt;
&lt;p&gt;&amp;Auml;lteste Synagoge Frankreichs (14. Jh.)&lt;/p&gt;
&lt;p&gt;Kathedrale von Cavaillon&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;https://www.avignon-et-provence.com/en/traditions/melon-festival-cavaillon&quot;&gt;Melonen-Festival&lt;/a&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;";

$champ_4="";

$champ_5="";

$champ_6="";

$champ_7="";

$champ_8="";

$champ_9="";

$champ_10="";

$champ_11="";

$champ_12="";

$champ_13="";

$champ_14="";

$champ_15="";

$champ_16="";

$champ_17="";

$champ_18="";

$champ_19="";

$champ_20="";

?>
